### ISSUE TITLE
HELP TICKET

### ISSUE THREAD

**Issue by nch66862** [nss-day-cohort-46/How-to-Ask-for-Help#10]
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board (Check these prior to creating the issue ticket)
These can be added in the column on the right
- [ x] Added label to specific project/assignment that you need help with
- [ x] Added to `Student-Help-Tracking` project board

#### REQUIRED Describe your issue:
>>I have a huge issues. Does this help ticket work?

#### REQUIRED List any error messages that appear:
```
Look at this error
```

#### REQUIRED What have you googled? (Paste links to the things you have found from your google search - You must have at least 3)
- [ ] 1. https://guides.github.com/features/mastering-markdown/
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>Looking at a markdown file

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
We will not accept links to the whole repo. You must provide a link directly to the specific file
**https://github.com/nss-day-cohort-46/sprinkles-of-joy-wookie-s-cookies/blob/71782959edd5c5089df26cc2a9e172764043413e/scripts/main.js#L6**

#### Code Snippet

```
cupcake.slice()
```

**Comment by Scott47** [comment]
this was a test. Thanks @nch66862 !
