### ISSUE TITLE
merge conflict- we are at lunch. will be back at 1! 

### ISSUE THREAD

**Issue by nicoletatum** [nss-day-cohort-46/How-to-Ask-for-Help#102]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X] Added to `c46 Help-Thread` project board
- [X] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> having an issue with being able to resolve merge conflict. I must've done something wrong in the terminal but i'm not sure how to resolve this issue. we have tried a few different things
#### REQUIRED Copy/paste any error messages that appear:

```
"src/components/ApplicationViews.js: needs merge
error: you need to resolve your current index first"
```
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. not sure what to google. I feel like issues are too tangled up to google.. if that makes sense.

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
1. checking out to a new branch
2. will not allow us to checkout to pre-existing branch 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/reactive-nutshell-hammer-of-guardians-1/pull/27/conflicts

#### Code Snippet

```
I would post but it would be so many lines of terminal code. I can if you would like. 
```

**Comment by ajawashington** [comment]
@nicoletatum I'll hop in your room after lunch.
