### ISSUE TITLE
Events filtering by user and sorting by date

### ISSUE THREAD

**Issue by morriscodez** [nss-day-cohort-46/How-to-Ask-for-Help#104]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I am struggling to figure out how to filter the events by current user and also how to sort them by date

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://upmostly.com/tutorials/react-filter-filtering-arrays-in-react-with-examples
- [ ] 2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf
- [ ] 3. https://www.geeksforgeeks.org/sort-an-object-array-by-date-in-javascript/

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have tried 

```
events.sort((a, b) => {
   new Date(b.date) - new Date(a.date)
}
```

and tried 

```
useEffect(() => {
        const filteredByUser = events.filter(e => e.userId === currentUserId)
        setUserEvents(filteredByUser)
    }, [])


              {
                    
                    userEvents.map(event => {
                        return <EventCard key={event.id} event={event} />
                    })
                }
```

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/c1e862594d24af6d4ce8992fdea59bdcb9627e4e/src/components/events/EventList.js#L21
```
```
https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/c1e862594d24af6d4ce8992fdea59bdcb9627e4e/src/components/events/EventList.js#L39
```

**Comment by jakefroeb** [comment]
For a sort method your callback function needs to return something so maybe try making it a one line function something like 
```
events.sort((a, b) => new Date(b.date) - new Date(a.date))
```

**Comment by Scott47** [comment]
what @jakefroeb said @dylanmorris51

**Comment by Scott47** [comment]
@dylanmorris51 , you can write it as a single line like @jakefroeb says . Otherwise, you need a `return` because you are making the `sort()` multiline. When it's a single line, there is an implicit return.

**Comment by morriscodez** [comment]
I'm trying that and still can't get it work

**Comment by morriscodez** [comment]
solved thanks for the help everyone! 

I was parsing as you suggesting Jake but never called that variable

**Comment by peytonkemp** [comment]
Sorting was killing me.. This helped!!
