### ISSUE TITLE
Live chat - question about direction to proceeed

### ISSUE THREAD

**Issue by notdanross** [nss-day-cohort-46/How-to-Ask-for-Help#105]
#### REQUIRED Question or issue:
>>I've tried implementing useEffect to watch a state variable to demo liveChat, but a users stat variables only update when they change something. We considered setting a function that checks for new data every 1 second, but we weren't sure if that is to heavy on fetch calls.

#### REQUIRED Check all that apply:
- [x] Direction/Guidance

#### Code Snippet

Snippet from our message list. "notification" is a state variable on the messageProvider.
https://github.com/nss-day-cohort-46/reactive-nutshell-nss-pendant-of-intellect/tree/dr-liveChat/src/components/messages

```
    useEffect(() => {
        getUsers()
            .then(getMessages)
    }, [notification])
```

**Comment by ajawashington** [comment]
@Daniel-L-Ross can you add a link to your branch plz?

**Comment by notdanross** [comment]
@ajawashington Here is the link: the notification state variable is declared in the provider and the useEffect is in messageList. 

https://github.com/nss-day-cohort-46/reactive-nutshell-nss-pendant-of-intellect/tree/dr-liveChat/src/components/messages

**Comment by notdanross** [comment]
SOLVED: By a careful reading of react documentation (and some tips from my esteemed colleagues) I was able to implement a simple solution that did not substantially modify existing code. 

https://reactjs.org/docs/hooks-effect.html#tips-for-using-effects
