### ISSUE TITLE
I need direction and help with friends/users searchbar

### ISSUE THREAD

**Issue by TrentSisson** [nss-day-cohort-46/How-to-Ask-for-Help#106]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue: I need some help thinking through my code and how to set up friends properly, I know I am going to have a lot to refactor. I am also having an issue setting the state of my search bar.
>>

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ https://dev.to/iam_timsmith/lets-build-a-search-bar-in-react-120j] 1. 
- [ https://forum.freecodecamp.org/t/updating-state-in-react-search-bar/163311] 2. 
- [ https://www.algolia.com/doc/api-reference/widgets/search-box/react/] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>I originally had the search bar on the friends list and I know that is not right but my search bar was working correctly, I changed the searchbar route to the home url and now it is not updating automatically, I have tried wraping list around it but nothing changed. I have been googling for a few minutes and I asked all of my team for help but they didnt have the answer either.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/reactive-nutshell-ring-of-sunfire-1/tree/TCS-friendsProvider
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by ajawashington** [comment]
@TrentSisson meet me in my instructor's room! I need to look more at this issue.
