### ISSUE TITLE
MessageCard not receiving data

### ISSUE THREAD

**Issue by kylieanyce** [nss-day-cohort-46/How-to-Ask-for-Help#107]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> MessageCard and MessageList seem to be set up correctly and have been working together all day. I recently added session storage and am working with the addMessage function, and now they have stopped communicating. when I console log, I can see that the data is being passed into messageCard, but it's throwing an error.

#### REQUIRED Copy/paste any error messages that appear:
TypeError: Cannot read property 'name' of undefined

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
1- data not being passed in react
not exactly sure what to google because it looks set up as it should and it has been working all day. Whatever I would google would likely be too vague to answer this?

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> googled a little, asked teammates to review it, tried debugging and console.log.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/kb-messageList/src/components/messages/MessageList.js**

#### Code Snippet

```
{
                    messages.map(message => {
                        const user = users.find(user => user.id === message.userId)
                        console.log(user, message)
                    
                        return <MessageCard key={message.id} message={message} user={user} />
                    })
                }
```

**Comment by ajawashington** [comment]
@kylieanyce on your message provider try expanding on the user on the get Request.

**Comment by kylieanyce** [comment]
@ajawashington that does get the return statement on the DOM again, but the javascript block isn't working. I'm still getting an error that user is undefined in message.js... Is this an example of having to let go of code that works and just rewrite the whole block?

**Comment by kylieanyce** [comment]
@ajawashington okay, I tried that and it displayed half of the info to the DOM but still wasn't sending any user data to messageCard, only message data. User was undefined in message.js. I refreshed the page a few times and now I'm getting an error that the fetch call isn't working at all. "unexpected T in JSON, 500 error"

**Comment by ajawashington** [comment]
@kylieanyce and when a debugger is added before this line [](https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/82b093ed93304ba7497c248564ad90e9454e18ae/src/components/messages/MessageList.js#L55) is the user data there?

**Comment by Scott47** [comment]
malformed JSON in file. Restart of json-server solved issue.

**Comment by kylieanyce** [comment]
@Scott47 @sageklein @ajawashington So... I cleared out the incorrect data in my database and restarted my JSON server, and the message board appears on the DOM. However, once I click the add message button, I get several errors. It seems to be iterating through the return about 10 times and console.logging my data, then adding one more message with userId undefined. I'm trying to assign the userId as the value of currentUserId (from session storage) but it doesn't seem to be grabbing that data. I'm getting the same error message of cannot read property name of undefined.

**Comment by ajawashington** [comment]
@kylieanyce make sure in your state variable userId is not 0 and is the currentUserId variable you defined.

**Comment by Scott47** [comment]
@kylieanyce had a double underscore for `const currentUserId = sessionstorage.getItem('nutshell__user')`
