### ISSUE TITLE
Quick question - Form Required not working

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#108]
**_Ticket MUST be completed before getting help from an instructor_**
#### Breakout Room:
Gauntlets-of-adventure
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added to `c46 Help-Thread` project board
- [ x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>
I have form required placed in the form but it is not working so that the button does not work and save if those fields are not saved

#### REQUIRED Copy/paste any error messages that appear:

none
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ https://codeburst.io/how-to-use-html5-form-validations-with-react-4052eda9a1d4] 1. 
- [ https://www.w3schools.com/react/react_forms.asp] 2. 
- [ https://stackoverflow.com/questions/30187781/how-to-disable-a-button-when-an-input-is-empty] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
I tried replacing the required to other areas within the input fields 
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/reactive-nutshell-gauntlets-of-adventure-1/blob/f0b9a103a50ccb9bb4a149adc107cb0488931cbd/src/components/news/NewsForm.js#L93
#### Code Snippet

```
<label htmlFor="newsArticleName">Article Title: </label>
            <input type="text" id="title" required autoFocus className="form-control"
            placeholder="Article title"
            onChange={handleControlledInputChange}
            value={newsArticle.title}/>
          </div>
        </fieldset>
        <fieldset>
          <div className="form-group">
              <label htmlFor="synopsis">Article's Synopsis:</label>
              <input type="text" id="synopsis" onChange={handleControlledInputChange} required autoFocus className="form-control" placeholder="Article synopsis" value={newsArticle.synopsis}/>
          </div>
        </fieldset>
        <fieldset>
          <div className="form-group">
              <label htmlFor="url">Article's Url:</label>
              <input type="text" id="url" onChange={handleControlledInputChange} required autoFocus className="form-control" placeholder="Articles url" value={newsArticle.url}/>
              
          </div>
        </fieldset>
       
        <button className="btn btn-primary"
          disabled={isLoading}
          onClick={event => {
            event.preventDefault() // Prevent browser from submitting the form and refreshing the page
            handleSavenewsArticle()
          }}>
        {newsArticleId ? "Save Article" : "Add Article"}</button>
      </form>
```

**Comment by ajawashington** [comment]
@Younique98 on your button on the form that onClick method. move that to your form tag and change it to onsubmit. and make sure your button has a type of submit. 

Should look like this: sent through slack

**Comment by ajawashington** [comment]
`<form className="newsArticleForm onSubmit={event => {
            event.preventDefault() // Prevent browser from submitting the form and refreshing the page
            handleSavenewsArticle()
          }}">
        <h2 className="newsArticleForm__title">{newsArticleId ? "Edit News Article" : "Add News Article"}</h2>
        <fieldset>
          <div className="form-group">
            <label htmlFor="newsArticleName">Article Title: </label>
            <input type="text" id="title" required autoFocus className="form-control"
            placeholder="Article title"
            onChange={handleControlledInputChange}
            value={newsArticle.title}/>
          </div>
        </fieldset>
        <fieldset>
          <div className="form-group">
              <label htmlFor="synopsis">Article's Synopsis:</label>
              <input type="text" id="synopsis" onChange={handleControlledInputChange} required autoFocus className="form-control" placeholder="Article synopsis" value={newsArticle.synopsis}/>
          </div>
        </fieldset>
        <fieldset>
          <div className="form-group">
              <label htmlFor="url">Article's Url:</label>
              <input type="text" id="url" onChange={handleControlledInputChange} required autoFocus className="form-control" placeholder="Articles url" value={newsArticle.url}/>
              
          </div>
        </fieldset>
       
        <button className="btn btn-primary"
          disabled={isLoading} type="submit"
          >
        {newsArticleId ? "Save Article" : "Add Article"}</button>
      </form>`

**Comment by jashah46** [comment]
Aja, I may have a similar issue. Can you slack that to me too? or Yasmeen?

**Comment by ajawashington** [comment]
@Younique98 could you put the solution to this issue and close out this ticket?
