### ISSUE TITLE
Never ending loop 

### ISSUE THREAD

**Issue by Ccourter11** [nss-day-cohort-46/How-to-Ask-for-Help#109]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
Rewrote my code so that when other people are searching for friends, it populates with users, it all works now, only thing is I have a never ending loop and i have no idea how to stop it yet.
>>

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://stackoverflow.com/questions/53070970/infinite-loop-in-useeffect
- [x] 2. https://medium.com/@andrewmyint/infinite-loop-inside-useeffect-react-hooks-6748de62871
- [x] 3. https://stackoverflow.com/questions/53243203/react-hook-useeffect-runs-continuously-forever-infinite-loop

#### REQUIRED: What have you tried? Tell us everything you have tried. 
Tried adding a second empty array bracket to no avail
>>

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
useEffect(() => {
        getUsers().then(() => {
        if (searchTerms !== "") {
            const subset = users.filter(user => user.name.toLowerCase().includes(searchTerms.toLowerCase()))
            setFilteredFriends(subset)
        }
        })
    }, [searchTerms, users])
```

**Comment by Scott47** [comment]
@Ccourter11 you are watching for users in the dependency array of your `useEffect()` , but you `getUsers()` promise calls `setUser` to set the state of `users`. 
https://github.com/nss-day-cohort-46/reactive-nutshell-shield-of-swiftness-1/blob/cc-friends-pr/src/components/users/UserProvider.js#L16

This changes the state of `users` and causes the `useEffect()` to run again. You will need to remove `users` from the dependency array.
