### ISSUE TITLE
Filter/Map/Find Timing Issues (I think)

### ISSUE THREAD

**Issue by blusanders** [nss-day-cohort-46/How-to-Ask-for-Help#110]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>

On Messages:

My goal is to determine whether the user who posted a given message is or is not the logged in user's friend.
If they are not a friend, then show an ADD FRIEND button next to the message.

I am pulling all Friends (I would eventually like to just pull logged in user's friends from the provider but all friends for now)
.then I'm filtering those friends for the user's friends, returning only the userId of the Friends array
then (not .then) I if that filtered array .includes the logged in user's id set a boolean or log out YES I AM YOUR FRIEND or whatever I need to do.
 
However, the filter is returning blank almost always but occasionally it's working so somewhere I'm getting lost in calling my data.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x ] 1. https://stackoverflow.com/questions/31058755/using-multiple-map-functions-vs-a-block-statement-in-a-map-in-a-java-stream
- [x] 2 https://stackoverflow.com/questions/679915/how-do-i-test-for-an-empty-javascript-object 
- [x] 3. http://www.discovermeteor.com/blog/understanding-javascript-map/ 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

I've been through this yesterday w my group, for several hours solo, and with Cheo this morning. 

No luck. Need help.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

https://github.com/nss-day-cohort-46/reactive-nutshell-gauntlets-of-adventure-1/blob/9956e9db4c598b86a3e00bff7a4604d646e75aa6/src/components/message/MessageCard.js#L19

#### Code Snippet

```
useEffect(() => {
        getFriends()
        .then(()=> {
            let myFriends = friends.filter(friend => currentUserId===parseInt(friend.currentUserId))
            console.log(myFriends)
            // let filteredFriends = myFriends.map(myFriend => parseInt(myFriend.userId))
            // console.log(filteredFriends)
            // setIsMyFriend(filteredFriends.includes(parseInt(message.userId)))
            // console.log(filteredFriends.includes(message.userId))
            // console.log(message.userId)
            // console.log(isMyFriend)
            // console.log(filteredFriends)

            if (isMyFriend) {
                console.log("YES FRIEND")
            }else{
                console.log("NO FRIEND")
            }
        })
    },[])```

**Comment by Scott47** [comment]
@blusanders First thing I notice is that you are not getting the value out of session storage. It should be `const currentUserId = parseInt(localstorage.getItem('nutshell_user')` Also, you do not need to `parseInt()` `myFriend.userId`.

https://github.com/nss-day-cohort-46/reactive-nutshell-gauntlets-of-adventure-1/blob/9956e9db4c598b86a3e00bff7a4604d646e75aa6/src/components/message/MessageCard.js#L14

**Comment by blusanders** [comment]
Well that was dumb. Copy that.

I'm still having weird issues.

**Comment by blusanders** [comment]
Moved my getFriends fetch call to Message List which made it only call getFriends one time rather than every time it was in a Message card. This solved the issue. Not totally sure why other than perhaps calling getFriends rapidly perhaps was causing everything to not be in sync?
