### ISSUE TITLE
Chat about API documentation for capstone

### ISSUE THREAD

**Issue by emilycentko** [nss-day-cohort-46/How-to-Ask-for-Help#111]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Wanted to chat about better understanding 3 API options and their documentations to use for capstone. Having a hard time getting started/navigating the API documentation and making sure I'm heading in the direction I need to go

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://tastedive.com/read/api
- [ ] 2. https://trakt.docs.apiary.io/#introduction/api-url
- [ ] 3. http://www.omdbapi.com/
- [ ] 4. https://developers.themoviedb.org/3/getting-started/introduction

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Looking through documentation, registering API keys to try to test them out

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
posted question to #ask-alumni-web-dev, got a great response from our awesome alum and has settled on an api.
