### ISSUE TITLE
Edit feature

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#115]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X] Added to `c46 Help-Thread` project board
- [X] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I am trying to route my edit button to render the TaskForm, so that I can edit 'tasks'
There is an issue with my fetch call and I can't figure it out... it has something to do with the asynchronous function.
I am not getting data back until after the first render.. so my edit function sees taskId as 'undefined'

The data is getting passed but in the wrong timing?

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://www.npmjs.com/package/react-edit-button
- [x] 2. https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
- [x] 3. https://reactjs.org/docs/hooks-effect.html
- [x] 4. https://marmelab.com/blog/2016/09/20/custom-react-router-component.html

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have tried console.log taskID... 
my taskDetails and taskForm seem correct but I can't get the fetch call to return the data in correct timing..
It returns data after the initial render but my Edit already fails before then.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**  https://github.com/nss-day-cohort-46/reactive-nutshell-gauntlets-of-adventure-1/blob/84444a865204dac94ef9d28883701f85f3fae15c/src/components/tasks/TaskProvider.js#L19

#### Code Snippet

TaskProvider
```
const getTaskById = (taskId) => {
        // debugger
        return fetch(`http://localhost:8088/tasks/${taskId}`)
            .then(res => res.json())
    }
```
TaskDetails
```
const handleDelete = () => {
    //   debugger
    deleteTask(tasks.id)
      .then(() => {
        history.push(`/tasks`)
      })
  }

  useEffect(() => {
    // debugger
    getTaskById(taskId)
      .then((res) => {
        setTasks(res)
      })
    }, [])
```

**Comment by nathanRomad** [comment]
gonna watch this after lunch and see if I can figure out this issue:  https://www.youtube.com/watch?v=NkT2yiv-NZ4

**Comment by Scott47** [comment]
Added `task` prop as parameter in form component, fixed routes in `ApplicationViews`, added a `useEffect()` to form, and changed `getTasks()` fetch to only get tasks for the currently logged in user.

**Comment by Scott47** [comment]
@nathanRomad I made a list of things we did ☝️ . As you are going through it and making comments, let me know if there is anything you need clarification on.

**Comment by kylieanyce** [comment]
@nathanRomad @Scott47  I am having this exact same issue but with editing the messages. Curious about the solution.
