### ISSUE TITLE
Edit button creating whole new event.

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#117]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ x Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Edit button creating a whole new event. 

#### REQUIRED Copy/paste any error messages that appear:

n/a
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. eventHandlera
- [ ] 2. updating objects in react
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Tried integating handleSaveEvent into handleClickSaveEvent

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/nss-day-cohort-46/reactive-nutshell-ring-of-sunfire-1/blob/main/src/components/Events/EventForm.js
#### Code Snippet

```
   const handleClickSaveEvent = (controlEvent) => {
        controlEvent.preventDefault() 
         addEvent(event)
         .then(() => history.push("/events"))
      }

       const handleSaveEvent = () => {
        if (parseInt(event.eventId) === 0) {
            window.alert("Please select a location")
        } else {
        
        } if  (eventId){
            //PUT - update
            updateEvent({
                id: event.id,
                name: event.name,
                date: event.date,
                eventId: parseInt(event.eventId),
                
            })
            .then(() => history.push(`/events/${event.id}`))
          } else {
            //POST - add
            addEvent({
                name: event.name,
                date: event.date,
                eventId: parseInt(event.eventId),
            })
            .then(() => history.push("/events"))
          }
        }
```

**Comment by jakefroeb** [comment]
your branch does not seem to be up to date but i imagine that you are calling the function handleClickSaveEvent, instead of your new function handleSaveEvent

**Comment by ajawashington** [comment]
@Thomas88s looking at the link you posted it doesn't have updateEvent being imported and also on this line 

https://github.com/nss-day-cohort-46/reactive-nutshell-ring-of-sunfire-1/blob/cd5df4423403181e5a5eb1d27f613dd119d3831b/src/components/Events/EventForm.js#L26 

should id be lowercase?

**Comment by Thomas88s** [comment]
I'm really not sure. Most of the group is at or around this part in their code and we were hoping someone code walk us through.

**Comment by jisie** [comment]
@Thomas88s Came into the breakout room and I think your volume was off. Let me know when most of the team is back from lunch and we can talk through edit.

**Comment by Thomas88s** [comment]
The event handler needed the eventId  to be able to know to update event.  My updateEvent function had" id: event.id" when it needed "id: eventId".
