### ISSUE TITLE
[QUICK ISSUE] 

### ISSUE THREAD

**Issue by samj0516** [nss-day-cohort-46/How-to-Ask-for-Help#118]
#### REQUIRED Question or issue: Caleb pulled my branch down to check my PR. It has an error, is looking for a (friends) file/component that doesn't exist on that branch. It worked fine on everyone else's machine. Why is it looking for something that doesn't exist on that branch? Branch is sc-TaskForm
>>

#### REQUIRED Check all that apply:
- [x] Rubber Ducking 
- [ ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by ajawashington** [comment]
@samj0516 @calebsjames did we add and commit our changes on our working branch before checking out to a new one?

**Comment by Scott47** [comment]
@samj0516 @calebsjames Was this an untracked changes issue like @ajawashington mentioned and is it resolved?

**Comment by samj0516** [comment]
@Scott47 @ajawashington he added/committed his branch before switching to mine. However, the errors popping up were on his previous branch. Not currently resolved yet

**Comment by samj0516** [comment]
So Caleb went back and fixed the errors that were on his branch, added/committed, then came back to my branch and the issue was resolved! Somehow the changes he had made on his branch must have followed him when he came to look at my branch. All good now :)
