### ISSUE TITLE
Need a one on one

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#119]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I just have no idea where to start on displaying all of the friends articles as well as the users. I just need to go in a room with an instructor and talk through what I need to do to get started. 

#### REQUIRED Copy/paste any error messages that appear:
Not applicable

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
I dont know where to start
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/LW-articles-friends/src/components/articles/ArticleList.js**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
added fetch to get friends by the currently logged in user. Needs to loop through friends and articles and match `articles.userId` to `friends.userId` and  `friends.currentUserId`

**Comment by morriscodez** [comment]
Try this:

```
 useEffect(() => {

        const matchingCurrentUserEvents = events.filter(event => (currentUserId === event.userId) )
            
        const matchingFriendEvents = events.filter(event => {
            return friends.map(friend => friend.userId === event.userId)
        })

        
        let filteredMatchingFriendEvents = []
        
        matchingFriendEvents.forEach(obj => {
            if (obj.userId !== currentUserId) {
                filteredMatchingFriendEvents.push(obj)
            }
        })
        
        const allEventMatches = matchingCurrentUserEvents.concat(filteredMatchingFriendEvents)

       
        

        setUserEvents(allEventMatches)

    }, [events, friends])

    
    Just replace events with articles.
    
    Make sure you're fetching all the articles and fetching the friend relationships for the sessonStorage user
    
    ## FriendProvider.js
    ```
    const getFriendsByCurrentUser = (id) => {
        return fetch(`http://localhost:8088/friends?currentUserId=${id}`)
            .then(res => res.json())
            // .then(setFriends)
    }
    ```
