### ISSUE TITLE
Friend Events Rendering

### ISSUE THREAD

**Issue by morriscodez** [nss-day-cohort-46/How-to-Ask-for-Help#121]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I am unable to get events to filter by userId of the friends table

#### REQUIRED Copy/paste any error messages that appear:

```
const matchingFriendEvents = friends.map(friend => events.userId === friend.userId)
        console.log('matchingFriendEvents: ', matchingFriendEvents);
```
console log returning as [false, false]

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. I am lost on what to google
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I am trying sorting events by current user Id and then sorting events by the userId of users who are friends with the Current User
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/9de8775797db8d5c8c8e04ac212779a914e8ef81/src/components/events/EventList.js#L35

#### Code Snippet

```
useEffect(() => {
        const matchingCurrentUserEvents = events.filter(event => (currentUserId === event.userId) )
        console.log('matchingCurrentUserEvents: ', matchingCurrentUserEvents);
        const matchingFriendEvents = friends.map(friend => events.userId === friend.userId)
        console.log('matchingFriendEvents: ', matchingFriendEvents);


    }, [events, friends])

```

**Comment by jisie** [comment]
@dylanmorris51 We are planning to cover this logic tomorrow with Logan. We can pull you in!

**Comment by morriscodez** [comment]
Solved:
``` useEffect(() => {

        const matchingCurrentUserEvents = events.filter(event => (currentUserId === event.userId) )
            
        const matchingFriendEvents = events.filter(event => {
            return friends.map(friend => friend.userId === event.userId)
        })

        
        let filteredMatchingFriendEvents = []
        
        matchingFriendEvents.forEach(obj => {
            if (obj.userId !== currentUserId) {
                filteredMatchingFriendEvents.push(obj)
            }
        })
        
        const allEventMatches = matchingCurrentUserEvents.concat(filteredMatchingFriendEvents)

       
        

        setUserEvents(allEventMatches)

    }, [events, friends])
```

Just needed to filter out the duplicate data from the nested loop. Nested loop is returning event objects for the session storage user which makes no sense to me but filtering that out works
