### ISSUE TITLE
Edit not prefilling form

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#122]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ X] Added to `c46 Help-Thread` project board
- [ X] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Have refactored my code but  it the articles is still not populating to be edited

#### REQUIRED Copy/paste any error messages that appear:
 No error message

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://dev.to/cesareferrari/handling-input-field-updates-in-react-47oe
- [ ] 2.  https://stackoverflow.com/questions/57584169/edit-form-not-updating
- [ ] 3. https://github.com/react-hook-form/react-hook-form/issues/456

#### REQUIRED: What have you tried? Tell us everything you have tried. 
Let team look at my code
>>

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/nss-day-cohort-46/reactive-nutshell-ring-of-sunfire-1/compare/am-nutshell-edit?expand=1#diff-8d554a9592de5dc8ec8d55a5f91375e87a475a76d9052d7e9840296999671db3R52

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by ajawashington** [comment]
@AndreaMays can you send a link to your branch and not your pr?

**Comment by SubtleCo** [comment]
Two quick things I noticed: 

-useParams on line 26 isn't invoked - add a "()" to useParams()

-getArticleById doesn't exist in the AricleProvider yet!

I added those two things and the article to edit appears in the form!

**Comment by ajawashington** [comment]
@AndreaMays what @SubtleCo said. Didnt even notice the useParams() was not invoked.

**Comment by ajawashington** [comment]
@AndreaMays for your provider 

const getArticleById = (id) => {
  return fetch(`http://localhost:8088/articles/${id}`)
      .then(res => res.json())
}

**Comment by AndreaMays** [comment]
@SubtleCo @ajawashington thank you so much. That worked! Quick follow up question, now that it's auto populating I can type in to edit the form, but what i type in is not being saved. I've looked at the if/else statement and checked my code again... i'm just struggling to find the bug

**Comment by AndreaMays** [comment]
Thank you!  

Answer to latter half of the question is the article.id was being turned into a string, so I had to "parseInt" my  "id" in the "UpdateArticle" in my "handleClickSaveArticle" in the "form".
