### ISSUE TITLE
Get Message By Id not working

### ISSUE THREAD

**Issue by kylieanyce** [nss-day-cohort-46/How-to-Ask-for-Help#123]
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes, and I commented on it
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I'm trying to edit a message and using params to get the specific one. It works. However, when I pass the id into getMessageById, the fetch call messes up somehow because the id is undefined.

#### REQUIRED Copy/paste any error messages that appear:
404 not found

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. fetch call not getting id react
- [ ] 2. id not passing to fetch in react
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I've tried debugging, console.logging, talking to teammates, googling, looking at issue tickets. Not sure what the next step is to figure this out.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/kb-editMessage/src/components/messages/MessageEditForm.js

#### Code Snippet

```
const getMessageById = (id) => {
        return fetch(`http://localhost:8088/messages/${id}`)
        .then(res => res.json())
    }
```
````
export const MessageEdit = () => {
    const { getMessageById, editMessage } = useContext(MessageContext)
    const [message, setMessage] = useState({})
    const currentUserId = parseInt(sessionStorage.getItem("nutshell_user"))
    const messageId = useParams()
    const history = useHistory()

    
    useEffect(() => {
            if (messageId) {
                getMessageById(messageId)
                .then(message => {
                    setMessage(message)
                })
            }
    }, [])
`````

**Comment by SubtleCo** [comment]
Hey @kylieanyce ! I think Params is an object that needs to be destructured. 

Maybe try `const { messageId } = useParams()` ?

**Comment by kylieanyce** [comment]
@SubtleCo Yes that worked!! Now on to fix this new error lol... Thank you!
