### ISSUE TITLE
[QUICK ISSUE] Join tables and accessing data from another re: friends

### ISSUE THREAD

**Issue by powellmad** [nss-day-cohort-46/How-to-Ask-for-Help#124]
#### REQUIRED Question or issue:
>> I need to clarify accessing data from join tables re: friends

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```

```

**Comment by ajawashington** [comment]
@powellmad To access friends I would make a friend provider, and when going to list friends just filter through where currentUserIds match. Is that what you are asking?

**Comment by powellmad** [comment]
You can either filter for ids that match or you can filter by including currentUserId in the fetch call. This will only show friends for the user of that id. You just need to set the id to the session storage id. 

http://localhost:8088/friends?_expand=user&currentUserId=${id}
