### ISSUE TITLE
route not working for history.push

### ISSUE THREAD

**Issue by kylieanyce** [nss-day-cohort-46/How-to-Ask-for-Help#127]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stopping you from moving forward

#### REQUIRED Describe your issue:
>> It appears that I have my route and history.push set up correctly, but it keeps the user on the same page instead of sending them to the details page. It also adds a ? to the end of the URL. It seems that when I hit submit, the page goes to the detail page for a split second then immediately redirects to the edit form again.

#### REQUIRED Copy/paste any error messages that appear:
n/a

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1.  why is history.push adding a '?' to the URL
- [ ] 2. why is there a "?" at the end of my URL
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> talking through with teammates, searching issue tickets, referencing code, googling. I also tried changing the ${} to say message.id instead of messageId, neither work. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1/blob/kb-editMessage/src/components/messages/MessageEditForm.js

#### Code Snippet

```
                .then(() => history.push(`/messages/detail/${messageId}`))
```

**Comment by jisie** [comment]
@kylieanyce Is the data being edited in the database? If not, then none of the code in your `handleEditMessage` might be executing. Try adding `event.PreventDefault()`

**Comment by kylieanyce** [comment]
@jisie it is editing my database correctly. Even if I simply want to route it back to the message list, that doesn't even work.

**Comment by kylieanyce** [comment]
Adding event.preventDefault() to the handleEditMessage function fixed it!
