### ISSUE TITLE
[QUICK ISSUE] Terminal Command Stopped Working

### ISSUE THREAD

**Issue by powellmad** [nss-day-cohort-46/How-to-Ask-for-Help#128]
#### REQUIRED Question or issue:
>> Code . stopped working about a month ago. Bryan tried to troubleshoot it with me and we never actually got it working. It only opens vscode, it doesn't open the current directory.

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

I put this in zshrc for now.

```
code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
```

**Comment by Scott47** [comment]
@powellmad if you added that to your .zshrc file and it is still not working, you may need to restart your terminal and maybe restart visual studio code.

Also, have you looked here?: https://code.visualstudio.com/docs/setup/mac

**Comment by powellmad** [comment]
@Scott47 I have looked at that article and restarted both. This has actually been an issue for over a month and I thought it was time to finally figure it out.

**Comment by Scott47** [comment]
reinstalled extension for VSCode to launch from the command https://code.visualstudio.com/docs/setup/mac
