### ISSUE TITLE
[QUICK ISSUE]

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#130]
#### REQUIRED Question or issue:
>> I am having an issue with 'npx create-react-app'
I have an existing repo setup but think there is something not installed in my terminal..

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [X] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

Terminal:
NPM ERR!

**Comment by jisie** [comment]
@nathanRomad You should not be setting up your code until you have had your one on one. You can create an empty repo for creating issues and the project board. The instructions for repo set up will be updated for Monday.

**Comment by nathanRomad** [comment]
ok.. I have my project board and am creating issues.
I was trying to setup and link the repo but I will happily wait until monday.

Thank you.
