### ISSUE TITLE
Capstone ERD

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#133]
#### REQUIRED Question or issue:
>> Thinking about my capstone, I'm not sure how to do my ERD.  Potentially, my capstone only one user and one dropdown that would filter information.  

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [X] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
Remember, that part of your requirements are to have CRUD (Create, Read, Update, Delete) on, at least, one resource in your `.json` file. Think through the entities you will be maintaining in your `database.json`. If the user is trying to optimize a draft, would they then save their players? If so, then you would need a players table in your erd with a userId as a foreign key for a one to many relationship. This is just a hypothetical example based on what I remember from your pre-proposal. Think through the information you want your user to save, what you'd want to display to the user, what the user can delete and edit. This will help you determine the resources you'll need to maintain with json-server.

**Comment by Scott47** [comment]
@jashah46 ☝️ Sorry, I forgot the @mention

**Comment by jashah46** [comment]
Thank you Scott!

**Comment by jashah46** [comment]
@Scott47
