### ISSUE TITLE
[QUICK ISSUE] Need to delete local repo, not working

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#134]
#### REQUIRED Question or issue:
>>I made the repo for my project, made all of the issue cards, then realized that I didnt create it as a react app. Now I need to delete the local repo and make a react repo to connect to my existing remote repo. I ran the rm -r command for my local repo and git this message  "rm: remove write-protected regular file 'oh-deer/.git/objects/df/4db5d4851ad3a34abdf72b84c8190e1a6b6172'?"

I have tried y + enter and yes + enter, but the message just keeps showing up.
#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
Not a code related issue
```

**Comment by Scott47** [comment]
@Loganwebb1994 make sure you are one level up from your local directory. Type `rm -rf <directory name>`

Then you can `npx create-react-app <appname>`

**Comment by Loganwebb1994** [comment]
@Scott47  Thanks!
