### ISSUE TITLE
[QUICK ISSUE] React and environment variables

### ISSUE THREAD

**Issue by SubtleCo** [nss-day-cohort-46/How-to-Ask-for-Help#135]
#### REQUIRED Question or issue:
>> I'd love to talk to someone about the security of environment variables in react, and namely why the documentation says:

"WARNING: Do not store any secrets (such as private API keys) in your React app! Environment variables are embedded into the build, meaning anyone can view them by inspecting your app's files."

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

in root: `.env.local`
in `.env.local`: `REACT_APP_API_KEY=********`

**Comment by jisie** [comment]
@SubtleCo This is going to come up when you host your application. So whatever hosting platform you use, you will have to look into how you can have runtime environment variables through the platform. Ideally, you want your client side app to make a request to a server side app which then uses the api key to get the data.

**Comment by SubtleCo** [comment]
@jisie Understood. So for now, the setup I listed above is fine? (given that `.env.local` is in `.gitignore`)

**Comment by jisie** [comment]
@SubtleCo Yup!
