### ISSUE TITLE
429 - Too Many Requests

### ISSUE THREAD

**Issue by KaitlinJKelley** [nss-day-cohort-46/How-to-Ask-for-Help#140]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I think my API is receiving too many calls close together because I'm mapping over routes and passing everything in at once

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://stackoverflow.com/questions/30471131/how-can-you-retry-after-an-exception-in-javascript-when-using-promises#comment49022795_30471209
- [ ] 2. https://stackoverflow.com/questions/38213668/promise-retry-design-patterns
- [ ] 3. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I tried implementing the retry-after header, but all the references declare a function to force a retry. Tried declaring a retry function but I keep getting red lines

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link: https://github.com/kjk1325/all-clear/blob/fc6417b0a53cbf95b4c7e3946081dc33950d3bda/src/components/routes/RoutePage.js#L36-L53**

#### Code Snippet

```
    useEffect(() => {
        if (userRoutes.length > 0) {
            debugger
            userRoutes.map(route => {
                if (userRoutes.length > 0) {
                    const promise = getIncidentAndLocation(route.origin, route.destination)
                    Promise.all(promise)
                        // Passes in an array of nested arrays, where each nested array contains a lat/long pair; line 61
                        .then(trafficIncidents => {
                            console.log(trafficIncidents)
                        })
                        .catch(error => {
                            console.log(error)
                        })
                }
            })
        }
    }, [userRoutes])
```

**Comment by jakefroeb** [comment]
Im not entirely sure but i think it is because your Promise.all is triggering every time through the map loop as the promises are fulfilling as they are being added to the promise array. which is then triggering the rest of your code. Try initializing promise outside the loop, then building your promise array in the loop, then after the array of promises has been built do the Promise.all(promise) outside of the loop

**Comment by Scott47** [comment]
Same error @jakefroeb @jisie We will need some help with this issue.

**Comment by KaitlinJKelley** [comment]
Had to refactor a very long chain of .thens and have to re-consider when to call the function because my API appears to have a rate limit.
Thanks @jisie for saving me from .then hell!
