### ISSUE TITLE
Mapping through an array and running fetch calls returns "Connection Refused" error

### ISSUE THREAD

**Issue by phillip-phan-imprivata** [nss-day-cohort-46/How-to-Ask-for-Help#141]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I am trying to map through an array of numbers and posting each number as an object to my JSON database. Sometimes, I am able to get all of the numbers to post, but my server crashes. Other times, I get the error "Connection Refused" and not all of the data makes it onto the database. 

#### REQUIRED Copy/paste any error messages that appear:

POST http://localhost:8088/grids net::ERR_CONNECTION_REFUSED

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://flaviocopes.com/javascript-async-await-array-map/
- [x] 2. https://stackoverflow.com/questions/33478714/promise-pattern-using-promise-all
- [x] 3. https://stackoverflow.com/questions/40140149/use-async-await-with-array-map

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Right now, I am mapping through the array and posting the object in the same function. I have tried mapping through the array and having the fetch post inside the map. I have tried using "async", "await", and "Promise.all" on both of these attempts. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

https://github.com/phillipphan/sketchbook/blob/pp-saveSketch/src/components/sketch/SketchProvider.js

#### Code Snippet

```
  const saveSketch = (obj) => {
    const savedSketch = {
      name: obj.name,
      userId: obj.userId
    }
    return fetch("http://localhost:8088/sketches", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(savedSketch)
    })
    .then(res => res.json())
    .then(sketch => {
      Promise.all(
        obj.grid.map(async gridItem => {
          await saveGrid({
            sketchId: sketch.id,
            gridId: gridItem
          })
        })
      )
    })
  }
```

**Comment by jisie** [comment]
Possible solution in the process of being tested. @phillipphan, please reach out if you continue to see the same error.

**Comment by phillip-phan-imprivata** [comment]
Instead of using the "map" method, I switched it to a "reduce" method that iterates through each promise and completes it before moving on to the next one. I believe the error came from the "map" method moving on to the next item in the array before the promise was fulfilled. No errors so far, but it may not be a permanent solution.

**Comment by phillip-phan-imprivata** [comment]
This fix only made the POST more consistent, but I still got errors if I used a bigger array than the one I was testing with. 

My new solution is to put this code into the provider:
```
const timer = ms => new Promise(res => setTimeout(res, ms))
```
I call this function whenever I need to make fetch calls while iterating through an array so that there is time in between each call.
