### ISSUE TITLE
Passing "searchTerms" to api

### ISSUE THREAD

**Issue by daprieu** [nss-day-cohort-46/How-to-Ask-for-Help#144]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added to `c46 Help-Thread` project board
- [x ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> My 3rd party API has the ability to search built in by passing a single letter or a word to the URL. I can create "dummy" code and put a phrase in and get an array of data but need help understanding how to pass a parameter to the fetch so that I can search the entire database instead of the initial search.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ https://www.toolsqa.com/rest-assured/query-parameters-in-rest-assured/] 1. 
- [https://dev.to/asimdahall/simple-search-form-in-react-using-hooks-42pg ] 2. 
- [ https://medium.com/@carlie.anglemire/search-bar-in-react-with-a-3rd-party-api-ced92c940236] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I am able to put dummy search in the api fetch call and search through the returned data. I tried to set searchTerm in a function call where I am getting my api and gave it a parameter

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/daprieu/Backyard-Botanist/blob/ap-searchPlants/src/components/searchPlants/SearchPlantsProvider.js**
**https://github.com/daprieu/Backyard-Botanist/blob/ap-searchPlants/src/components/searchPlants/SearchPlantList.js**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
@daprieu Will you please paste the link to the code in your repo?

**Comment by daprieu** [comment]
> @daprieu Will you please paste the link to the code in your repo?

I updated the ticket with two links (one for my provider and the other where I am using searchTerms to filter the data)
I just had a thought that the .filter with searchterms is just filtering data that is already available so I know I will need to refactor that code. Because what I really want is to pass a search term to the api url query and get back that specific  query search data.

**Comment by Scott47** [comment]
@daprieu You have defined your `getSearchablePlants()` function to take a name as a parameter in your provider, but you are not passing it anything in your searchList component. https://github.com/daprieu/Backyard-Botanist/blob/3de215e28b89296ea84815b9a28db431853dcb68/src/components/searchPlants/SearchPlantList.js#L13

**Comment by Scott47** [comment]
whoops @daprieu . Realizing now that your issue is the problem I am describing here 🤦 . I'll come see you after stand up.

**Comment by daprieu** [comment]
Solved! (for the most part - weird issue marginally related) 

In my code I was trying to use .filter to filter my api data based on searchTerms.
In reality when adding searchTerms to my API call it was already filtering the data. 
I removed the .filter portion in the second useEffect and added searchTerms to the the getSearchablePlants() in the first useEffect.
