### ISSUE TITLE
Having a routing issue 

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#146]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Having a issue getting my provider to show because my AppViews isn't routing it. I am not finding any spelling errors and may just need an extra set of eyes.

#### REQUIRED Copy/paste any error messages that appear:
./src/components/store/Store.js
Module not found: Can't resolve '../AppViews' in '/Users/macbookpro/workspace/around-again-records/src/components/store'

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. I've ran into this issue several times and its usually a misspelling or a missing ./ 
- [ ] I
- [ ] 
- [ ] 2.
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>Back tracking . spell check. comparing with old code 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/Thomas88s/AroundAgainRecords/blob/tw-listingRecords/src/components/store/Store.js
#### Code Snippet

```

import React from "react"
import { AppViews } from "../AppViews"
import "./Store.css"

export const Store = () => (
    <>
        
       <AppViews />
    </>
)

```

**Comment by ajawashington** [comment]
@Thomas88s in your imports looks like you need to go out one more level to get access to the AppViews.

**Comment by Thomas88s** [comment]
It was a basic routing issue caused by syntax errors.  This probably could have been avoided if I had taken more breaks today.
