### ISSUE TITLE
Rendering a single random object from the api

### ISSUE THREAD

**Issue by powellmad** [nss-day-cohort-46/How-to-Ask-for-Help#147]
#### REQUIRED Question or issue:
>> I'm trying to work out the necessary logic for rendering a single, random quote from my api. I have tried a few methods and just need to talk it through

#### REQUIRED Check all that apply:
- [x] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet - The Methods I Just Tried:

```
const randomQuoteId = () => {
        return quotes[Math.floor(Math.random() * this.length)]
    }


    const getQuotes = () =>
        return fetch(`http://localhost:8088/quotes/${randomQuoteId.id}`)
        .then(res => res.json())
        .then(setQuotes)
    }
```
I know this logic doesn't work because quotes is not set until the fetch call, but the function is within the fetch call.

```
  return (
    <div className="quoteComponent">
        {console.log("QuoteList: Render", quotes)}
        <h2>Quotes</h2>
        
        <div className="quote-selection">
            { quotes.map(quote => {
                return <QuoteCard key={quote.id} quote={quote} /> }
            )}
        </div>
        <button onClick={() => {history.push("/")}}>
        Next Quote
        </button>
    </div>
  )
}

const randomQuote = () => {
    return quotes[Math.floor(Math.random() * this.length)]
}
```
I think I need to put it in the component that renders the list, I'm just not sure how.

**Comment by powellmad** [comment]
I know this logic doesn't work because quotes is not set until the fetch call, but the function is within the fetch call.

**Comment by powellmad** [comment]
I'm thinking inside the quotes.map I need to put a .find to get the quote with the same id and the random number

**Comment by powellmad** [comment]
Tried this and the .find is undefined

```
<div className="quote-selection">
            { quotes.map(quote => {
                const randomQuote = quotes.find(quote => quote.id === randomQuoteId)
                return <QuoteCard key={quote.id} quote={quote} /> }
            )}
        </div>

**Comment by powellmad** [comment]
I had redundant code that was throwing up a string of errors. I didn't need to map through quotes because randomQuoteId was doing that for me. Once I got a random id, I just had to call QuoteCard and pass in the random id.

```
const randomQuoteId = quotes[Math.floor(Math.random() * quotes.length)]

return (
<div className="quote-selection">
        <QuoteCard quote={randomQuoteId}/>
        </div>
)
```

**Comment by powellmad** [comment]
I added and committed these changes and merged it with main. No changes were made and no merge conflicts appeared on the pull request, but this code is now broken again ?

**Comment by ajawashington** [comment]
Need to add a conditional on card so that it doesn't break on first render. `{quote?.mastertext}`
