### ISSUE TITLE
I have a quick question about my fetch call

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#148]
#### REQUIRED Question or issue:
>> I think i'm going to need to pull pretty much all of my data with one fetch call and I was just wondering what would be the best way to do that. Im trying my best to google expand and embed attributes but Im not finding anything helpful

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [x] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
changed fetch to `/userstands?_expand=user&_expand=stand`

**Comment by Loganwebb1994** [comment]
I thought I was good. I just need to talk to someone about how to fetch my data
