### ISSUE TITLE
React bootstrap [QUICK ISSUE]

### ISSUE THREAD

**Issue by peytonkemp** [nss-day-cohort-46/How-to-Ask-for-Help#151]
#### REQUIRED Question or issue:
>>  just need some instruction on how to implement the things I want

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
@peytonkemp Is this resolved?
