### ISSUE TITLE
[QUICK ISSUE] Child Key Error - doesn't seem to be affecting app

### ISSUE THREAD

**Issue by blusanders** [nss-day-cohort-46/How-to-Ask-for-Help#154]
#### REQUIRED Question or issue:
>>
I'm getting the prop/key error in the console but am not sure what it's referring to and it doesn't seem to be affecting my app at all.
index.js:1 Warning: Each child in a list should have a unique "key" prop.

#### REQUIRED Check all that apply:
- [x] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Crew`. See https://reactjs.org/link/warning-keys for more information.
    at CrewCard 

```

**Comment by Scott47** [comment]
@blusanders This is a warning. You can put a key prop on the div that doesn't have one or ignore.

**Comment by blusanders** [comment]
Copy that. Thank you. Just couldn't find it but I'll look for rogue div. That makes sense.
