### ISSUE TITLE
[QUICK ISSUE] ERD additions

### ISSUE THREAD

**Issue by SubtleCo** [nss-day-cohort-46/How-to-Ask-for-Help#155]
#### REQUIRED Question or issue:
>> I need approval for some ERD additions, found here:
[ERD issue ticket](https://github.com/SubtleCo/TipHat/issues/41)

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

**Comment by ajawashington** [comment]
@SubtleCo Hit up your mentor and get your ERD approval from them! 

edited: GREAT issue ticket as well!

**Comment by SubtleCo** [comment]
@ajawashington @jisie asked me to open a ticket here to reminder her

**Comment by ajawashington** [comment]
@SubtleCo Oh okay cool! Sorry I closed it 👀
