### ISSUE TITLE
[HELP TICKET]

### ISSUE THREAD

**Issue by hrlnsnchz** [nss-day-cohort-46/How-to-Ask-for-Help#16]
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board (Check these prior to creating the issue ticket)
These can be added in the column on the right
- [x ] Added label to specific project/assignment that you need help with
- [x ] Added to `Student-Help-Tracking` project board

#### REQUIRED Describe your issue:
>> We're console logging 2 variables before they're passed into a function call as parameters. We don't get an error message, but the variables are being logged as "[object object]"

#### REQUIRED List any error messages that appear:
```
PASTE ERROR MESSAGE HERE
```

#### REQUIRED What have you googled? (Paste links to the things you have found from your google search - You must have at least 3)
- [ ] 1.https://stackoverflow.com/questions/34573792/javascript-function-to-return-object-returns-object-object
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> We tried changing the scope of the variables when assigning them their value

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
We will not accept links to the whole repo. You must provide a link directly to the specific file
**Your link: https://github.com/nss-day-cohort-46/sprinkles-of-joy-palpatine-amandine/blob/3b3c5ffe6f46b0a83f27e8181f52d229ba0fdcd9/scripts/products/ProductList.js#L24**

#### Code Snippet

```
const render = (bakeryProducts, bakeryCategories) => {
  contentTarget.innerHTML = bakeryProducts.map(product => {
    const productCategory = bakeryCategories.find(category => category.id === product.categoryId)
    console.log("Product" + product, "category" + productCategory)
    return Product(product, productCategory)
  }).join("")
}
```

**Comment by jisie** [comment]
@hrlnsnchz In your console.log, when you use the `+`, you are doing string concatenation. That converts the object to a string. Try taking out the `+`.
