### ISSUE TITLE
trying to render a dropdown bar and the info when clicked

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#160]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added to `c46 Help-Thread` project board
- [ x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I keep running into an error message due to trying to create a drop down menu that populates the horoscopes for selection and displays the info from the api from that when selected

#### REQUIRED Copy/paste any error messages that appear:

TypeError: Cannot destructure property 'horoscopes' of 'Object(...)(...)' as it is undefined.
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export] 1. 
- [ https://www.w3schools.com/css/css_dropdowns.asp] 2. 
- [https://crunchtech.medium.com/object-destructuring-best-practice-in-javascript-9c8794699a0d ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
I have tried rewriting the function using a useEffect so that It can getHoroscopes then filter through those horoscopes to grab the selected one. 
Then I tried to return HoroscopeCard after mapping over the selectedHoroscope
I also tried to create a new api that housed the horoscope names, and info about that. 
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/Younique98/the-magical-witch/blob/fa618906b33df9f0b976363e73505a8137d34380/src/components/Container/Change.js#L112
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
`const [selectedHoroscope, setSelectedHoroscope] = useState([])

    useEffect(() => {
        getHoroscopes()
    }, [])

    useEffect(() => {
        const selected = horoscopes.filter(horoscopes.sign.toLowerCase())
        setSelectedHoroscope(selected)
    }, [])
``
`` <div className="chooseSignonSignUp"><p>Choose Your Sign</p></div>
        <div class="dropdown">
        <button class="dropbtn">Dropdown</button>
        <div class="dropdown-content">
            {selectedHoroscope.map(horoscope => {
                return <HoroscopeCard key={horoscope.id} horoscope={horoscope} />
            })}
         
  </div>
</div>
    
    </div>
    ``

**Comment by jisie** [comment]
@Younique98 is the process of refactoring her code based on changes to the ERD. Please reach out when you are ready to tackle this issue.

**Comment by jisie** [comment]
@Younique98 I don't know if this is still an issue that you are seeing. If it's not, can you please close it? You can reopen it if you encounter it again.
