### ISSUE TITLE
App not displaying

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#161]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added to `c46 Help-Thread` project board
- [x ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>App not rendering. Cards are rendering but when app is inserted it breaks.

#### REQUIRED Copy/paste any error messages that appear:

./src/AppViews.js
Module not found: Can't resolve 'react-router-dom' in '/Users/macbookpro/workspace/around-again-records/src'

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ x] 1. react app not rendering 
- [ x] 2. Can't resolve 'react-router-dom'
- [ ] 3. react router problems

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>search, referencing other code, backtracking

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/Thomas88s/AroundAgainRecords/blob/tw-addingrecords4/src/components/store/Store.js 
#### Code Snippet

```
import React from "react"
import { RecordCard } from "../records/RecordCard"
import { AppViews } from "../../AppViews"


// import { NavBar } from "../nav/NavBar";
import "./Store.css"

export const Store = () => (
    <>
        <h1>Around Again Records</h1>
       <AppViews />
       <h2>Records</h2>
       
        <article className="records">
            <RecordCard />
            <RecordCard />
            <RecordCard />
        </article>
    </>
)
```

**Comment by ajawashington** [comment]
@Thomas88s on this lline https://github.com/Thomas88s/AroundAgainRecords/blob/d7e4dbdd3498689143b71e2f6f7be51acf0cc794/src/index.js#L9

you need a Router to be wrapped around your `<Store/>` 

Example 

`ReactDOM.render(`
`<React.StrictMode>`
`<Router>`
` <Store />`
`<Router/>`
  `</React.StrictMode>,`
 ` document.getElementById('root')`
`);`

make sure to `import { BrowserRouter as Router } from "react-router-dom"`

**Comment by ajawashington** [comment]
@Thomas88s also want to make sure your `<Store/>` component includes your Application Views as well since that is where your app is going.

**Comment by Scott47** [comment]
Also @Thomas88s did you install react-router-dom with `npm install --save react-router-dom`

**Comment by Thomas88s** [comment]
It includes the appViews. Ive been having issues with the route too , ive tried it a few times and it throws errors.

**Comment by Thomas88s** [comment]
ill try the npm. I ve been having a lot more trouble than i think i should be. i did this stuff last week with no trouble

**Comment by Scott47** [comment]
> ill try the npm. I ve been having a lot more trouble than i think i should be. i did this stuff last week with no trouble

You have to install the react-router-dom package to use Routes

**Comment by Scott47** [comment]
Resolved by installing react-router-dom package
