### ISSUE TITLE
[QUICK ISSUE]

### ISSUE THREAD

**Issue by daprieu** [nss-day-cohort-46/How-to-Ask-for-Help#164]
#### REQUIRED Question or issue:
>> Need a way to get the last Id of an object from local database to use in POST method.

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
    const addPlantNote = (plantObj) => {
        return fetch("http://localhost:8088/plantnotes", {
        method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(plantObj)
        })
        
    }
```

**Comment by SubtleCo** [comment]
@daprieu Oh you're gonna love this. A post in a fetch request returns the object on success.

I.e.
```
addPlantNote(plantObj)
   .then(newlyStoredObject => console.log(newlyStoredObject.id))
```


At least I hope that's what you were asking because when I realized this I was so excited

**Comment by daprieu** [comment]
Thanks @SubtleCo!!! I will use this in the future but turns out I did not need to get data this way.
