### ISSUE TITLE
Adding Workout Videos to Workouts

### ISSUE THREAD

**Issue by morriscodez** [nss-day-cohort-46/How-to-Ask-for-Help#169]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I need to figure out how to add Videos to my Workouts.

user can create a "Workout" which means naming a container that will hold several selected videos.

So do I add an input dropdown on my create workout form that has videos the user can select while creating the workout?

Or do I create the workout then navigate to a different page to add videos to the workout?

My preferred option would be to create the workout then navigate to the video library where the user can just click a button on the video they like and it adds it to the workout they created, or gives them a choice of which "workout" to add that video to

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://reactjs.org/docs/faq-functions.html
- [ ] 2. https://www.pluralsight.com/guides/how-to-reference-a-function-in-another-component
- [ ] 3. https://stackoverflow.com/questions/48407785/react-pass-function-to-child-component

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have tried making a form like we did in Nutshell and it works for adding a workout, but not for adding videos to that workout. I think what I need to do is add a State Variable to my video library page for my "workoutVideos" join table that joins videos with workouts, and everytime that button is clicked the button adds that video as an entry on the workoutVideo join table with the correct workoutId, so when the workouts page loads it loads everything from the database with that workoutId.

Then I can have a delete button on that card as it displays in the "workouts" section which deletes that entry from the "workoutVideos" join table.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/dylanmorris51/spotter/blob/ed6600d78171ed07c89c8919f255954de553ce4a/src/components/videos/VideoCard.js#L22
#### Code Snippet

```
export const VideoCard = ({ video }) => (
    <Card style={{ width: '18rem' }}>
        <Card.Header>{ video.exerciseType?.type }</Card.Header>
            <Link to={`/videos/detail/${video.id}`}>
                <Card.Img variant="top" src={video.img} />
            </Link>

        <Card.Body>
            <Card.Title>{ video.name }</Card.Title>
            <Card.Subtitle>{ `Helps with ${video.painType?.type} pain` } </Card.Subtitle>
            <Card.Text>
            </Card.Text>
            <Button variant="primary" onClick={() => {
                //! Add this workout to the join table

                
            }}>
                Add to Workout
            </Button>
        </Card.Body>
    </Card>
)
```

**Comment by morriscodez** [comment]
Further clarification:

I am not sure whether to build the function to add this workout video to the join table right here on the card component or in a separate component and import it and call it at this spot in the card component.

I want to follow single responsibility, but if I build it separately how do I pass the values through props?

**Comment by ajawashington** [comment]
@dylanmorris51 I am closing this for now for you to try the things we talked about. Feel free to reopen if you still have issues.
