### ISSUE TITLE
Making multiple fetch requests simultaneously

### ISSUE THREAD

**Issue by SubtleCo** [nss-day-cohort-46/How-to-Ask-for-Help#171]
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes - related to #140 and #141 
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Trying to make a POST request inside of a loop makes the last few requests fail

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://stackoverflow.com/questions/53377774/fetch-multiple-links-inside-foreach-loop
- [x] 2. https://www.npmjs.com/package/json-server#routes
- [x] 3. https://stackoverflow.com/questions/57868537/post-collection-of-objects-in-json-server

#### REQUIRED: What have you tried? Tell us everything you have tried. 
- running the code below
- running each iteration inside of a setTimeout with a 10ms difference
- running each iteration with a debugger (works fine)
- sticking the fetch inside of a for loop that awaits the response to increment i

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
https://github.com/SubtleCo/TipHat/blob/d1dbe8c404410bcfd65033b19c5c771717b24164/src/components/liveReports/LiveReport.js#L70

#### Code Snippet

```
const artistNameArray = reportTable.map(artist => artist.name)
artistNameArray.forEach((aN, i) => {
   if (!checkForArtist(aN)) {
      addArtist(aN)
   }
```

**Comment by jisie** [comment]
@SubtleCo I have two suggestions for you to try.

1. Try restarting your json-server without the `-w` flag so `json-sever -p 8088` and see if your requests still fail.
1. Your loop just creates the fetch calls and and you use a `Promise.all()` to execute the fetch calls.

Let me know if either solution works!

**Comment by SubtleCo** [comment]
BEAUTIFUL, removing the watch flag works. Thanks!

**Comment by jisie** [comment]
@SubtleCo The disadvantage of running json-server without the watch flag is that if you manually edit the json file, it won't pick the changes. So make sure to re start the server if you change the file through an editor.

**Comment by SubtleCo** [comment]
@jisie haha, oh trust me - I learned that the hard way!
