### ISSUE TITLE
getIdby fetch call is returning undefined for the id

### ISSUE THREAD

**Issue by dtracydepp** [nss-day-cohort-46/How-to-Ask-for-Help#173]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>My fetch call for getIdby is returning error and undefined for the id

#### REQUIRED Copy/paste any error messages that appear:

 GET http://localhost:8088/friends/undefined?_embed=items 404 (Not Found)

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://stackoverflow.com/questions/44524424/get-http-localhost3000-404-not-found
- [ ] 2. https://www.npmjs.com/package/json-server
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>checked my database, copied code exactly from ItemProvider that is working fine , changed the route, checked in postman

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:https://github.com/dtracydepp/dude-wheres-my-stuff/blob/72000f1af20a54d159e1fe61be344be387cfee8f/src/components/friends/FriendProvider.js**

#### Code Snippet

```
Provider
 const getFriendById = (id) => {
        return fetch(`http://localhost:8088/friends/${id}?_embed=items`)
            .then(res => res.json())
          
    }
```

**Comment by jisie** [comment]
@dtracydepp This is the route in `ApplicationViews`:

```js
<Route exact path="/allfriends/">
    <FriendSelect />
 </Route>
```

Your route is not defined to include a parameter. But in your `FriendSelect` you are using `useParams()` to try to grab a parameter, `friendId` from the URL and eventually pass this to your `getFriendById`.

**Comment by dtracydepp** [comment]
I added one and it made everything disappear and no errors and my console log stopped working so I deleted it to take it back to this point to do the issue ticket. but maybe I did something else wrong. I’ll try it again after lunch with fresh eyes.

**Comment by dtracydepp** [comment]
1. I didn’t have my route wrapped and what Jisie said 
2. I skipped steps and had to backtrack before I need to getFriendsbyID
