### ISSUE TITLE
[Quick Issue] I would like to walk through the next step for nav bar

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#175]
#### Breakout Room:
Erica
#### REQUIRED Question or issue:
>>
I would like to walk through how to link localhost:3000 to my NavBar which I will be reconfiguring to look like my Figma.
This will be changed to Home, Horoscope Notes, Tarot Notes, Login, SIgnup
#### REQUIRED Check all that apply:
- [x ] Rubber Ducking 
- [x ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet
https://github.com/Younique98/the-magical-witch/blob/6aef8814711d048d09d7b3c68a428f7fe3ae01c3/src/components/Nav/NavBar.js#L12
```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```
  <Link className="nav-link" to="/Horoscope">Horoscopes</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/horoscopeComments">Saved Horoscopes</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/register">Sign Up</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/tarot">Tarot Reading</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/login">Login</Link>

**Comment by Scott47** [comment]
@Younique98 Sent you DM on slack. Let me know if you still want to talk through this and I'll meet you in my instructor room
