### ISSUE TITLE
Several issues inclunding git,  broken code, guidance needed 

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#176]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added to `c46 Help-Thread` project board
- [x ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>first Id like to revert my main back to my last merge
2 im having an issue with my edit button duplicating items and fields not being pre filled during edit
3 id like some direction for making viewing of records user specific 

#### REQUIRED Copy/paste any error messages that appear:
nsrc/components/records/RecordForm.js
  Line 25:10:  React Hook useEffect has a missing dependency: 'getRecords'. Either include it or remove the dependency array                                     react-hooks/exhaustive-deps
  Line 89:8:   React Hook useEffect has missing dependencies: 'getRecordById', 'getRecords', and 'recordId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. ive google reverting git back  but  i dont trust it . 
- [ ] 2. how to get back code from git
- [ ] 3. how to revert back to last merge

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
going back to previous branch, fixing code, referring to other code, a hammer
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

https://github.com/Thomas88s/AroundAgainRecords/pulls?q=is%3Apr+is%3Aclosed
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
made sure we were selecting correct id for record, added auth for currentUserId
