### ISSUE TITLE
push in right direction(many to many tables)

### ISSUE THREAD

**Issue by nicoletatum** [nss-day-cohort-46/How-to-Ask-for-Help#183]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X] Added to `c46 Help-Thread` project board
- [] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>
I need a push in the right direction for adding "tools" and "materials" to my "project form." I'm not sure if I could reference previous code or not. 

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
not really sure what to google I just need some help getting started 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>1.referencing previous projects

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/nicoletatum/Craft-Corral/blob/main/src/components/ProjectsBoard/AddProject.js

#### Code Snippet

`N/A`

**Comment by Scott47** [comment]
needed to import `getTools()` and `tools` from `ToolProvider.js` to be able to map through the tools array and populate the dropdown for the projects form.
