### ISSUE TITLE
Edit button is saving a new round card rather than editing that card

### ISSUE THREAD

**Issue by peytonkemp** [nss-day-cohort-46/How-to-Ask-for-Help#185]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>  Edit button is saving a new round card rather than editing that card

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1.   https://stackoverflow.com/questions/55149022/how-to-create-an-edit-button-in-react 
- [x] 2.  https://stackoverflow.com/questions/50147030/react-edit-form-creating
- [x] 3.  https://medium.com/dev-genius/reactjs-form-editable-473e48fb6c9e

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I'm pretty stuck and don't know what to try.  Would love some help

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/peytonkemp/front-end-capstone/blob/main/src/components/rounds/RoundForm.js

#### Code Snippet

```
return (
        <form className="roundForm">
            <h2 className="roundFormTitle">{roundId ? "Edit Round" : "Add Round"}</h2>
            <fieldset>
                <select onChange={handleControlledInputChange}>
                    <option value="0">Please select a course...</option> {
                        courses.map(course => {
                            return <option value={course.id}>{course.name}</option>
                        })
                    }
                </select>
                <div>
                    <label htmlFor="roundScore">Round Score</label>
                    <input type="text" name="roundScore" id="score" onChange={handleControlledInputChange} required className="form-control" placeholder="Strokes" value={round.score}></input>
                </div>
                <div>
                    <label htmlFor="roundDate">Date Played</label>
                    <input type="text" name="roundDate" id="date" onChange={handleControlledInputChange} required className="form-control" placeholder="ex. 6/25/20" value={round.date}></input>
                </div>
            </fieldset>
            <button className="btn btn-primary"
              onClick={event => {
                event.preventDefault()
                handleSaveRound()
            }}>
              {roundId ? "Save Round" : "Add Round"}
            </button>
        </form>
    )
```

**Comment by Scott47** [comment]
@peytonkemp Change your route in application views to `exact path="/edit/:roundId(\d+)`.  This will get you to the correct route. Now, you are going to edit/:roundId for add round and edit round.

**Comment by peytonkemp** [comment]
@Scott47 I changed the application views to include `exact path="/edit/:roundId(\d+)` but changing the history.push wasn't getting to me where I wanted

**Comment by peytonkemp** [comment]
@Scott47 Also, I am getting a "PUT 400 (Bad Request)" error whenever I click my Edit Round button

**Comment by Scott47** [comment]
@peytonkemp change `getRoundById()` to take `roundId` as a parameter and change the url int the fetch from `http://localhost:8088/rounds/edit/${round.id}` to `http://localhost:8088/rounds/${roundId}`.

Next, in `RoundForm.js`, use the `roundId` you are getting via params in your route to pass to the `getRoundById()` function in your `useEffect()`. 
```
useEffect(() => {
        getRounds().then(getCourses).then(() => {

            if (roundId) {
                getRoundById(roundId)
                .then(round => {
                    setRound(round)
                })
            }
        })
    }, [])
```

Once you make these changes, your form will have the values for the round the user selects pre-populated. The next step for you will be to PUT the object in the database when the user clicks the `Save Round` button.

**Comment by peytonkemp** [comment]
My updated round object is successfully being PUT in the database, BUT I cannot figure out why i’m not returning to the previous url after saving. It feels like I’ve tried everything I can with the `history.push`.  Right now I have `.then(() => history.push("/"))` and I feel like that should take me back to localhost:3000.  What am I missing?

**Comment by Scott47** [comment]
@peytonkemp Will you post a link to the current code on the branch you're workin on?

**Comment by Scott47** [comment]
@peytonkemp uncomment the `event.preventDefault()` on your button in your `Roundform` component.
