### ISSUE TITLE
Selecting course from dropdown returns value of 0. I need the course Id

### ISSUE THREAD

**Issue by peytonkemp** [nss-day-cohort-46/How-to-Ask-for-Help#186]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>  I need the course id when selecting a course from the dropdown in the 'round form.' I am getting a value of 0.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://stackoverflow.com/questions/47860931/how-to-map-over-an-object-which-has-a-unique-id-for-each-object-values-and-retur
- [x] 2. https://stackoverflow.com/questions/50956462/getting-id-from-div-in-react-js/50956718
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>  parseInt. event.target.value.   I know it involves one or both of those but I think I am using them in the wrong place.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/peytonkemp/front-end-capstone/blob/main/src/components/rounds/RoundForm.js

#### Code Snippet

```
<select onChange={handleControlledInputChange}>
                    <option value="0">Please select a course...</option> {
                        courses.map(course => {
                            return <option value={course.id}>{course.name}</option>
                        })
                    }
                </select>
```
```
 if (roundId) {
                updateRound({
                    courseId: parseInt(round.courseId),
                    score: round.score,
                    date: round.date,
                    userId: round.userId
                })
                .then(() => history.push("/"))
            } else {
                addRound ({
                    courseId: parseInt(round.courseId),
                    score: round.score,
                    date: round.date
                })
                .then(() => history.push("/"))
            }
```

**Comment by Scott47** [comment]
add value, name, id attributes on select element. Added key prop to option.
