### ISSUE TITLE
Need help getting logged in

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#20]
Thomas Witherow

tattooine
 
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `Student-Help-Tracking` project board

#### REQUIRED Describe your issue

Passwords arent working and unable to get logged in.
Tried entering existing logins but getting nothing.

#### REQUIRED What have you googled? "javascript Invalid email and/or password"

- [ ] 1. https://www.w3resource.com/javascript/form/email-validation.php
- [ ] 2.  https://stackoverflow.com/questions/16350287/validating-email-and-password-using-javascript
- [ ] 3. https://www.edureka.co/blog/javascript-email-validation/

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>Looked at comments to this ticket.  Added debugger and tried to follow it.  We found emails and passwords that were "null".  We backtracked and looked for the source of these items and hit a wall. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by nicoletatum** [comment]
We would also like help with this. can we hop over to the room when they are getting help or should we make our own help thread OR just work on something else and come back to see the updated help thread with solution? Thanks!

**Comment by jisie** [comment]
If you are getting the alert box with the message `Invalid email and/or password. Please try again.`, find where that is written in the code and work backwards to see why that conditional is executing the `else` instead of the `if`.

**Comment by nicoletatum** [comment]
^ yes. we struggled with this too. 

 
1. what Jisie said. see what file you need to go into 
2. See if you have the right selectors in the event listener(#, . )
 (We put a __debugger_ in the event listener and it helped us work backwards)
3.See if you are grabbing just the container or the contents within..

Hope this helps! Guess my middle name and you might just get your first born child back. (rumpelstiltskin ref. not trying to be creepy)
I'm sorry my programming vocabulary isn't the best.

**Comment by jashah46** [comment]
You need to make sure that the class selectors are uniform and match where the data is to entered. So if you have a class make sure you are selecting a class in your query selector.

**Comment by Thomas88s** [comment]
The eventhub querySelectors for the  login and password needed to have the .value specified at the end.
