### ISSUE TITLE
Im having trouble getting my data to pull at first render

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#202]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> Before I added two more list components, my check in checkout feature was working fine. After I added the lists its saying .filter isnt a function when I try and filter my join tables to get my notes. It only throws the error when I check in though. So It renders the notes from the join table, just not when I hit check in.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. I need a workshop on googling.. I have no idea what to look for in this issue. Maybe when someone comes to help they could tell me what they would have searched in this situation. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I tried to put a ? before the filter, but its still throwing the error

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/Loganwebb1994/oh-deer/blob/LW-filtering-reserved/src/components/stands/StandList.js**
**https://github.com/Loganwebb1994/oh-deer/blob/LW-filtering-reserved/src/components/stands/AvailableStands.js**
**https://github.com/Loganwebb1994/oh-deer/blob/LW-filtering-reserved/src/components/stands/ReservedStands.js**

#### Code Snippet

```
export const AvailableStands = () => {
  const history = useHistory()
  const { stands, getStands, getUserStands, userStands, getUsers } = useContext(StandContext)


  useEffect(() => {
    getUserStands()
    .then(getStands)

  }, [])

  const filteredStands = stands.filter(stand => stand.availability === true)
  
  
  return (
  <>
  <button onClick={() => history.push("/")}>All Stands</button>
    <div className="standList">
      {
        filteredStands.map(stand => { let notesForStand = userStands.filter(userStand => userStand.standId === stand.id  )
          return <StandCard key={stand.id} stand={stand} relationships={notesForStand} />
        })
      }
    </div>
  </>
  )
}
```

**Comment by jakefroeb** [comment]
maybe try switching the order of your get functions in your useEffect?

**Comment by Loganwebb1994** [comment]
I'll try that, thanks jake!

**Comment by Loganwebb1994** [comment]
Nawp.. Same thing happened.

**Comment by Loganwebb1994** [comment]
I cant move forward until this issue is resolved. The notes feature is dependant on the user being currently checked into the stand.

**Comment by Scott47** [comment]
@Loganwebb1994 In your `StandProvider.js`, your `reserveStand` fetch is a POST method and has `.then(setUserStands)`. Because this is a POST, you are setting `userStands` as an object. `.filter()` is an array method, so that is why you are getting this error. Delete the `.then` on line 40 of `StandProvider.js` and you should be good to go.

**Comment by Loganwebb1994** [comment]
@Scott47 I can check in and out now, but it doesnt show the name of the person checking in now

**Comment by Scott47** [comment]
@Loganwebb1994 I do not think these issues are related. Could be wrong, but spend some time with it and let us know what you find.

**Comment by Loganwebb1994** [comment]
@Scott47 I added a use effect to the card component to get the users and its showing the occupant again.
