### ISSUE TITLE
Editing unable to change value

### ISSUE THREAD

**Issue by SLLittrell** [nss-day-cohort-46/How-to-Ask-for-Help#204]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>When routed to the edit garden form, I would like the inputs to be prepopulated with the current data, I  am getting a red warning, and I am unable to change the values. 

#### REQUIRED Copy/paste any error messages that appear:

```
index.js:1 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at div
    at fieldset
    at form
    at GardenForm (http://localhost:3000/main.f3146005bb7374b95d16.hot-update.js:551:63)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:58433:29)
    at GardenProvider (http://localhost:3000/main.f3146005bb7374b95d16.hot-update.js:843:87)
    at UserProvider (http://localhost:3000/static/js/main.chunk.js:4271:83)
    at ApplicationViews
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:58433:29)
    at BlossomBuddies
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:58068:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:57688:35)
```

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://reactjs.org/docs/forms.html
- [ ] 2. https://medium.com/byte-sized-react/controlled-forms-in-react-68e59362a119
- [ ] 3. https://stackoverflow.com/questions/44786669/warning-use-the-defaultvalue-or-value-props-on-select-instead-of-setting

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

- Removing initial values, able to input data and update object
- adding defaultValue, able to change inputs but will not save data that did not get changed

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/SLLittrell/NSS-Blossom-Buddies/blob/sl-edit-garden/src/components/gardens/GardenForm.js#L83
#### Code Snippet

```
<form>
                <h3>{gardenId ? "Edit your Garden" : "Create a Garden"}</h3>
                <fieldset>
                    <div className="garden_form">
                        <label htmlFor="name">Name: </label>
                        <input type="text" id="name" value={gardens.name} autoFocus className="gardenInput" 
                        onChange={inputChange}/>
                    </div>
              </fieldset>
```

**Comment by jisie** [comment]
@SLLittrell You have two state variables you seem to be try to be using. `garden` and `gardens`. You are using both and you need to stick to using the same state variable. If this is a form to add/edit a garden, then use `garden`. 

This means on the input fields, you need for example `value={garden.name}`. And your `useEffect` that pre-populates the form needs to use the same state variable: `setGarden(garden)`

**Comment by Scott47** [comment]
@SLLittrell I see you closed this. Was it resolved? Was ☝️ the solution?

**Comment by SLLittrell** [comment]
Changed to only use one state variable in the garden edit form. This solved the warning when initial values are rendered in input fields.
