### ISSUE TITLE
Link changes url, but does not trigger a render

### ISSUE THREAD

**Issue by SLLittrell** [nss-day-cohort-46/How-to-Ask-for-Help#206]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>when clicking on the appropriate affordance the link changes url to the correct path, but the component does not render.

#### REQUIRED Copy/paste any error messages that appear:

No ERROR message occurs 

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://stackoverflow.com/questions/43351752/react-router-changes-url-but-not-view
- [x] 2. https://forums.meteor.com/t/link-changes-url-but-does-not-rerender-the-component/44027
- [x] 3. https://ui.dev/react-router-v4-url-parameters/

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

- changing the button path to links connecting to list items
- reworking when data needed, is rendered
- Googling

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/SLLittrell/NSS-Blossom-Buddies/blob/sl-helper-links/src/components/plants/PlantDetail.jsx#L26
#### Code Snippet

```
export const HelperListDividers = ({helpers, plantFilter}) => {
  const classes = useStyles();
  const matchPlant =plantFilter?.find(name => helpers?.includes(name.commonName.toLowerCase()))
  // const helperId = matchPlant ? `/plants/details/${matchPlant?.id}` : "/plants"
  console.log(matchPlant)

 
  return (
    <List component="nav" className={classes.root} aria-label="helpers">
      <Link to={`/plants/details/${matchPlant?.id}`}><ListItem >
        <ListItemText primary={helpers} />  
      </ListItem></Link>
      <Divider light />
    </List>
  );
}
```

**Comment by jisie** [comment]
@SLLittrell Can you reply and tell us what the url looks like? Also use your components tab in your dev tools to see if the `<PlantDetails />` component is being rendered at all.

**Comment by SLLittrell** [comment]
The link is using an id # from a plant that matches the name of a helper plant. When the link is clicked the url changes to:

http://localhost:3000/plants/details/37
37 being the id of the tomato plants details page.

When navigating to tomatoes from the plant list component this renders fine, and even if I refresh the page after the link is clicked it will route to the correct details page.

**Comment by jisie** [comment]
@SLLittrell I see your route in ApplicationViews and I don't see anything wrong with it. When you click on the link and the URL changes, are you getting any errors or just a blank screen?

**Comment by SLLittrell** [comment]
@jisie No Errors or warnings. It stays on the page with the link, and from what I can tell from some console logs it does a re-render of that page.

**Comment by SLLittrell** [comment]
**Resolved**
-Added id params to the plant data useEffect dependency array, so when the link is clicked the component knows to re-render.
