### ISSUE TITLE
useEffect and filtering objects

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#208]
**_Ticket MUST be completed before getting help from an instructor_**
#### Breakout Room:
Thomas
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I have 2 text input search bars. The second one works fine but the first doesn't. I'm thinking its a useEffect problem being that I have them stacked back to back. Not sure.  Do i need an additional list function to put it in?  Can these be combined?

#### REQUIRED Copy/paste any error messages that appear:
N/A

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. useEffect
- [x] 2. Using multiple useEffects
- [x] 3. useEffect with multiple dependencies

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
web search, rewriting, backtracking
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

https://github.com/Thomas88s/AroundAgainRecords/blob/main/src/components/collections/CollectionList.js

#### Code Snippet

```
useEffect(() => {
   if (searchTerms !== "") {
    //  if user types an input this displays a match
     const subset = records.filter(record => record.name.toLowerCase().includes(searchTerms))
     setFiltered(subset)
   } else {
     setFiltered(records)
   }
   
  }, [searchTerms, records]) 
  

  useEffect(() => {
    if (searchTerms !== "") {
     //  if user types an input this displays a match
      const subset = records.filter(record => record.artist.toLowerCase().includes(searchTerms))
      setFiltered(subset)
    } else {
      setFiltered(records)
    }
   }, [searchTerms, records]) 


  return (

    <>
      <h1>Records</h1>
      <div className="records">
      {
        filteredRecords.map(record => {
          return <CollectionCard key={record.id} record={record} />
        })
      }
    </div>
    </>
  )
}
```

**Comment by jisie** [comment]
@Thomas88s If you want two different search terms that you need to use, then you need a state variable for each one. And then you need to filter using both search terms.

**Comment by Thomas88s** [comment]
That worked. I added a new state and .map to my List component and now I'm able to search both with no problems.
