### ISSUE TITLE
How do I access my standId from my StandNoteForm?

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#209]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I just need tp speak to an instructor. Im not sure how to capture the id of the stand to use in my standNoteForm. 

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. Nothing to google here
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I dont know where to start

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/Loganwebb1994/oh-deer/blob/LW-noteform/src/components/stands/StandNoteForm.js**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
When you click the add note button, push to a route with the stand id. You have access to this in your StandCard, so change `history.push("/add-note")` to `history.push(`/stands/${stand.id}`)` . This way you will have access to the id you need when the user adds a note via the `useParams()` hook.

**Comment by Loganwebb1994** [comment]
My saveNote function is throwing a bunch of errors. not sure why. 
```
   const addNote = (currentUserId, noteString) => {
        fetch(`http://localhost:8088/userStands?userId=${currentUserId}`, {
        method: "PATCH",
        body: JSON.stringify({
          note: {noteString}
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8"
        }})
      }


```
```
const saveNote = (event) => {
        event.preventDefault()
        addNote(currentUserId, note)
        .then(() => history.push("/"))
    }
```

**Comment by Loganwebb1994** [comment]
Errors: TypeError: Cannot read property 'preventDefault' of undefined
and when I comment out that line that has the preventDefault() it says cant read property .then() of undefined

**Comment by Loganwebb1994** [comment]
Current error: TypeError: Cannot read property 'then' of undefined referring to this line  ```.then(() => history.push("/"))```

**Comment by Scott47** [comment]
@Loganwebb1994 Your error means that the thing that precedes the `.then` is undefined, so look in to what the `.then` is chained to.

**Comment by jisie** [comment]
@Loganwebb1994 Scott is right. You need to make sure a Promise is returned when chaining the `.then`. 

But also, when you are doing a PATCH, you need the id of the userStand you want to edit. So your URL for your PATCH request needs to be `http://localhost:8088/userStands/${userStandId}`. Remember, if the item already exists in the database and you need to take an action on it (DELETE, PUT, PATCH), then you need to have the id in the URL. And there should be NO filtering in the URL for a PATCH request: `userId=${currentUserId}`

**Comment by Scott47** [comment]
@jisie we are blocked on this issue. The join has a standId and a userId. We can check for the currently logged in user and for the stand. However, we are not able to access the id for the userStand to pass to the PATCH. In fact, there can be multiple instances for userStand for that user on that stand. I'm not sure what we are missing.

**Comment by Loganwebb1994** [comment]
```
,
    {
      "userId": 1,
      "standId": 1,
      "note": {
        "note": "can we edit?"
      },
      "id": 5
    }
```
The patch is saving something to the Db but not in the format I need.

**Comment by ajawashington** [comment]
@Loganwebb1994 Your patch request should look like this 

 const addNote = ( noteString, userStandId) => {
        fetch(`http://localhost:8088/userStands/${userStandId}`, {
        method: "PATCH",
        body: JSON.stringify({
          userStand: {
         note: {noteString}
         }
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8"
        }})
      }

**Comment by Loganwebb1994** [comment]
I actually had to do notestring.note @ajawashington It works now :)

**Comment by Scott47** [comment]
Stored id for userStand in state variable in the provider.
