### ISSUE TITLE
[QUICK ISSUE] filtering

### ISSUE THREAD

**Issue by peytonkemp** [nss-day-cohort-46/How-to-Ask-for-Help#211]
#### REQUIRED Question or issue:
>>   I could use a nice little nudge in the right direction in getting started with this 'filter by...' dropdown

#### REQUIRED Check all that apply:
- [x] Rubber Ducking 
- [x] Direction/Guidance
- [x] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by Scott47** [comment]
@peytonkemp Now that you have a solution to this problem, add it to this issue ticket. It will help you think through the logic. Maybe add comments to what you implemented and then paste it in here before you close out the issue.

**Comment by peytonkemp** [comment]
```
    useEffect(() => {
        if (filteredCourses !== "0") {
            const filter = rounds.filter(round => {
                return round.courseId === parseInt(filteredCourses)
            })
            setFilteredRounds(filter)
        } else {
            setFilteredRounds(rounds)
        }
    }, [filteredCourses])
```
and put an onChange on the select tag
```
<select className="dropdownBox" value={rounds.courseId} name="courseId" id="courseId" onChange={(e) => setFiltered(e.target.value)}>
```
