### ISSUE TITLE
Cannot Destructure property error

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#216]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [ X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X ] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I'm not sure what this error is talking about or how fix it as the code looks similar to all of my other "UseContext" code.

#### REQUIRED Copy/paste any error messages that appear:

TypeError: Cannot destructure property 'deleteProduct' of 'Object(...)(...)' as it is undefined.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://stackoverflow.com/questions/64924634/cannot-destructure-property-value-of-object-as-it-is-undefined
- [ ] 2. https://stackoverflow.com/questions/65157591/typeerror-cannot-destructure-property-of-object-as-it-is-undefined
- [ ] 3. https://stackoverflow.com/questions/62441256/react-typeerror-cannot-destructure-property-as-it-is-undefined

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Talking through it with someone else. Googling.  

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/AndreaMays/Frontend-Capstone/blob/am-cstone-renderFormToDom/src/components/Users/UserMenuCard.js#L6
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by jisie** [comment]
@AndreaMays This error usually occurs when you haven't wrapped the provider component around the component that is trying to access the data: https://github.com/nashville-software-school/client-side-mastery/blob/master/book-4-nashville-kennels/chapters/LIST_USECONTEXT.md#wrap-the-animallist-with-data
