### ISSUE TITLE
Using a PATCH request, not in a table (last feature before mvp)

### ISSUE THREAD

**Issue by powellmad** [nss-day-cohort-46/How-to-Ask-for-Help#219]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [ ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I am using a PATCH request to grab the id of a jedi master from a "card" and replace the forgein key of masterId on my users object so that the current logged in user sees the master they have chosen (their masterId).

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
- [x] 2. https://medium.com/@9cv9official/what-are-get-post-put-patch-delete-a-walkthrough-with-javascripts-fetch-api-17be31755d28
- [x] 3. https://stackoverflow.com/questions/66429667/how-to-make-a-patch-request-in-reactjs

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link: https://github.com/powellmad/light-side/blob/1d3b139edd809b0c8eb805bb5bca096302bc04cb/src/components/masters/MasterProvider.js#L14**

#### Code Snippet

```
const updateMaster = id => {
        return fetch(`http://localhost:8088/masters/${id}?`, {
          method: "PATCH",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
              masterId: ""
          })
        })
          .then(getMasters)
      }
```

**Comment by jisie** [comment]
@powellmad If you are updating a userObject then your PATCH request should be made to `http://localhost:8088/users/${id}`. The fetch call you currently would be trying to update an actual master object itself. You are not editing the master, you are editing the user, specifically `masterId` FK on a user object. Also, are you getting an errors?

**Comment by powellmad** [comment]
@jisie Thank you! I updated the pathway to /users. I don't have error but I'm stuck on where/how to call updateMaster (my patch) so that I get the id of the master that the users selects and pass it into updateMaster.

**Comment by jisie** [comment]
@powellmad What component does the user pick another master in? Or where do you need to call it from? If you can provide a link to that component, that would be awesome.

**Comment by powellmad** [comment]
I added an onClick to the div holding each card. The onClick calls the patch (updateMaster) via the selectMaster function and passes in UpdatedUserObject. When the Jedi Master Card is clicked, the id of that master is passed into masterId, which is rendered on home.

```
const selectMaster = () => {
        const updatedUserObject = {
            id: currentUser,
            masterId: master.id
        }
        updateMaster(updatedUserObject)
        .then(() => history.push("/"))
    }

    return (
        <div className="master master__{master.id} " onClick={selectMaster}>
            <h4 className="master__name">{master?.name}</h4 >
            <div className="master__avatars">
                <img className="master__avatar" src={`./jedi/${master.image}.png`} alt={`${master?.image}`} />
            </div>
        </div>
    )
