### ISSUE TITLE
[QUICK ISSUE] CSS issues

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#228]
#### REQUIRED Question or issue:
>> I cannot get my cards to flex and i've tried wrapping them, rubber ducking, googling...etc

#### REQUIRED Check all that apply:
- [X ] Rubber Ducking 
- [ X] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
.userCardOrder {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-evenly;
    box-shadow: 4px 4px 20px rgb(165, 141, 88);
    transition: 0.5s;
    border-radius: 10px;
    height: 550px;
     
}
```

**Comment by Scott47** [comment]
refactored to select parent and flex for direct children of the parent element.
