### ISSUE TITLE
[QUICK ISSUE] Ch 1 Install errors 

### ISSUE THREAD

**Issue by blusanders** [nss-day-cohort-46/How-to-Ask-for-Help#230]
#### REQUIRED Question or issue:
>>
Install errors on 3rd party software

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
pipenv install autopep8 watchgod

```

**Comment by blusanders** [comment]
virtual env starts but installs won't work

**Comment by hannahhall** [comment]
Needed to check the folder `pipenv shell` was run in. If accidentally run in the home folder, you'll need to remove the pipfile and virtual environment
```
rm ~/Pipfile
exit
rm -rf <path to virtual environment>
```
