### ISSUE TITLE
Vim from git merge main issue

### ISSUE THREAD

**Issue by samj0516** [nss-day-cohort-46/How-to-Ask-for-Help#24]
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Blu is stuck in VIM hell after attempting to git merge main into his branch! help!

#### REQUIRED List any error messages that appear:
No proper error message

#### REQUIRED What have you googled? 

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
I've tried these steps. This is a common screen and have yet to figure out how to get out of it.

https://code.likeagirl.io/help-i-was-using-git-to-commit-some-code-and-now-the-window-has-changed-and-i-dont-know-what-s-9348a27e145b

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by jisie** [comment]
@samj0516 Try this:

1. Esc
2. Shift + :
3. Type in `wq`
4. Enter

**Comment by blusanders** [comment]
It was the SHIFT.      Small things 1  Blu 0
