### ISSUE TITLE
cannot get category select to render to DOM

### ISSUE THREAD

**Issue by kylieanyce** [nss-day-cohort-46/How-to-Ask-for-Help#25]
#### Name:
Kylie and Nick

#### Group:
Wookie's Cookies

#### Book / Chapter: 
Sprinkle of Joy

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [ x] Added label to specific project/assignment that you need help with
- [x ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
Cannot get category select menu to appear on DOM. 

#### REQUIRED List any error messages that appear:
n/a

#### REQUIRED What have you googled? 
The code looks good, so we aren't sure where to start googling, need help figuring that out. Nick googled ".innerHTML not displaying" with no luck yet.

#### REQUIRED: What have you tried? Tell us everything you have tried. 
Looked for others with same issue on issue board, rubber ducky, debugger, console.log for errors, get none. tried to think of things to google but struggling.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/nss-day-cohort-46/sprinkles-of-joy-wookie-s-cookies/blob/main/scripts/categories/CategorySelect.js

#### Code Snippet

```
const render = () => {
  debugger
  contentTarget.innerHtml = `
      <select class="dropdown" id="categorySelect">
          <option value="0">All baked goods...</option>
          ${categories.map(category => `<option value="${category.id}">${category.name}</option>`).join("")}
      </select>
  `
}
```

**Comment by jisie** [comment]
@kylieanyce @nch66862 Make sure you are accessing the right property on your DOM element: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML.

If it it the right property, make sure you check for spelling and casing.

**Comment by kylieanyce** [comment]
@jisie we checked this and seems good, but we just figured out that innerHTML was spelled wrong! It was like this:
```
.innerHtml
```
and it needs to be like this:
```
.innerHTML
```
