### ISSUE TITLE
Event Listener is not working

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#28]
#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ X] Added label to specific project/assignment that you need help with
- [X ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>Trying to get the contact form event listener to listen for the click. I've created the event listener. 

#### REQUIRED List any error messages that appear:
 No error messages

#### REQUIRED What have you googled? 

- [ ] 1. https://www.youtube.com/watch?v=LqBmbgD_2Ig
- [ ] 2. https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault
- [ ] 3. https://www.w3schools.com/tags/tag_dialog.asp

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Talked to my teammate. Worked on it for an hour and half. Talked through the code to myself. Googled

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/sprinkles-of-joy-tuskan-raider-truffles/commit/45174ac093ce06ba124d279586a944be44417f5f
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by Scott47** [comment]
changed  ``` 
<li id="contactForm"><a href"#">Contact</a></li>
```  in `index.html`

to 
```
<li><a  id="contactForm" href"#">Contact</a></li>
```

The `clickEvent.target.id` is the inner most element. Since the a tag is what is nested, it needs to own the id for the `clickEvent`.
