### ISSUE TITLE
Having trouble Getting cart to go away after the logout/placeOrder 

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#30]
#### Name:
Logan Webb
#### Group:
Kylo Ren

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
Once the customer logs out the customer nav bar and the cart stay. 

#### REQUIRED List any error messages that appear:
No Errors

#### REQUIRED What have you googled? 

- [x] 1. https://developer.mozilla.org/en-US/docs/Web/API/Storage/clear
- [x] 2.  https://javascript.info/localstorage#sessionstorage
- [x] 3. https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> We have tried in MANY ways to set the container equal to an empty string with no luck
- tried: setting productsInOrder = []
- tried: if else in the render function for openCart()
- tried: setting userCart = ""

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/nss-day-cohort-46/sprinkles-of-joy-kylo-ren-s-rice-krispie-treats/blob/main/scripts/customers/CustomerNav.js**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by jisie** [comment]
@Loganwebb1994 Is the code you have tried on branch? The link to the file in the issue takes use to `CustomerNav.js` on main.

**Comment by Scott47** [comment]
@Loganwebb1994 @CheoR @nathanRomad Please add the resolution to this issue before closing.

**Comment by nathanRomad** [comment]
We are getting items from the menu to add to the cart.
We are getting items in the cart to save into our database when placeOrder is clicked.

We can't figure out how to clear the cart after placeOrder is clicked.

**Comment by jisie** [comment]
@nathanRomad @CheoR @Loganwebb1994 Is this still an issue you guys are working on?

**Comment by Scott47** [comment]
Closing this ticket since it was edited instead of resolving the issue. Please make a new ticket if you have a new issue.

**Comment by nathanRomad** [comment]
We were misunderstanding the new help thread flow and did not realize we could see instructor comments on the branch..
Our group was waiting for this issue to get picked up but didn't realize there were already comments from instructors..
Several times, we came back to the 'help thread' and did not see the comments... you have to click SEE ISSUE FULL DETAILS. 

So, we moved on to another issue and are re-prioritizing the features we are working on.

We will be trying to clear the cart when a user logs out but will establish a correct and NEW issue ticket if we get stuck on this issue again.
