### ISSUE TITLE
EventListener and star review to leave ratings

### ISSUE THREAD

**Issue by emilycentko** [nss-day-cohort-46/How-to-Ask-for-Help#31]
#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> We could use a little help on understanding the structure of our components and chat through how to set up our ProductReview form and eventually how the ratings will then render along with ProductList. We have an EventListener listening for "showNewReviewForm" that is giving us an error message and unclear if the way we have ratings included in our form is on the right track. (Haven't gotten to saved reviews yet - trying to get initial page load for form to render first!)

#### REQUIRED List any error messages that appear:
Cannot read property 'addEventListener' of null

#### REQUIRED What have you googled? 

- [ ] 1. https://www.cssscript.com/simple-5-star-rating-system-with-css-and-html-radios/
- [ ] 2. https://medium.com/@ishitaa.ashley4/simple-star-rating-css-and-javascript-8c450046ba2b
- [ ] 3. https://codeburst.io/a-simple-star-rating-system-using-vanilla-js-css-and-html-caf1b3e4d9f1

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Tried googling, referencing old code especially from NoteForm in Glassdale and mood dropdowns in Daily Journal. Also tried debugging after EventListener clicks

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/nss-day-cohort-46/sprinkles-of-joy-death-star-danishes/tree/ec-leave-reviews/scripts/reviews

#### Code Snippet

```
eventHub.addEventListener("showNewReviewForm", event => {
    renderForm()
})

const renderForm = (prodctsArray) => {
    const stringOfProductOptions = prodctsArray.map(product => `option value="${product.id}">${product.name}</option>`)
    contentTarget.innerHTML = `
                <label for="review-dropdown">Leave a Review for: </label>
                <select id="review--product" class="reviewProduct">
                    <option value="0">Please select a product to review</option>
                    ${stringOfProductOptions.join("")}
                </select>

                <label for="review-title">Title: </label>
                <input type="text" id="review--title">
            
                <label for="review-body">Review: </label>
                <input type="text" id="review--body">
            
                <label for="review-rating">Rating: </label>
                <input type="radio" id="review--rating">
                    <div class=”fa fa-star checked” id=”one”></div>
                    <div class=”fa fa-star unchecked” id=”two”></div>
                    <div class=”fa fa-star unchecked” id=”three”></div>
                    <div class=”fa fa-star unchecked” id=”four”></div>
                    <div class=”fa fa-star unchecked” id=”five”></div>

            <button id="save--review">Leave a Review</button>
    `
}
```

**Comment by jisie** [comment]
This error usually means whatever precedes the `. addEventListener` is null. Look into where you declare `eventHub`. Are you targeting the right element on the DOM?

**Comment by emilycentko** [comment]
@jisie Updated target element to "#container" for eventHub, thank you for catching that!
