### ISSUE TITLE
Returning Reviews to dom

### ISSUE THREAD

**Issue by bpotts11** [nss-day-cohort-46/How-to-Ask-for-Help#32]
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
I am working on rendering reviews to the DOM. I am getting an error that .map is not a function. I think that is because I am not getting the information to the variable that I am supposed to. I have tried to delete the .map to just see if the click events are listening to each other, and when I do this the event listener loads on page load. I am a little lost as to what direction I need to take right now

#### REQUIRED List any error messages that appear:

ReviewList.js:19 Uncaught (in promise) TypeError: customerReviews.map is not a function
    at render (ReviewList.js:19)
    at ReviewList.js:14

#### REQUIRED What have you googled? 

- [ ] 1.  https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
- [ ] 2. https://stackoverflow.com/questions/2373995/javascript-addeventlistener-event-fires-on-page-load
- [ ] 3. https://forum.freecodecamp.org/t/map-is-suddenly-not-a-function/134196

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have compared to previous code. Tried different approaches with where I put the event listener. I have googled.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
The EventListener
https://github.com/nss-day-cohort-46/sprinkles-of-joy-canoli-clones/blob/bp-review-feature/scripts/reviews/ReviewList.js

The Event
https://github.com/nss-day-cohort-46/sprinkles-of-joy-canoli-clones/blob/bp-review-feature/scripts/products/ProductList.js

#### Code Snippet
The Event Listener
```
eventHub.addEventListener("ReviewsClicked", event => {
    console.log("this is in reviewList.js --- Review click heard")
    const selectedProductId = event.detail.productId
    const productArray = useProducts()
    const selectedProduct = productArray.filter((product) => product.id === selectedProductId)
    ReviewList(selectedProduct)
})
```
The Event
```
eventHub.addEventListener("click", event => {
    if (event.target.id.startsWith("reviews--")) {
        const [prefix, productId] = event.target.id.split("--")
        const customEvent = new CustomEvent("ReviewsClicked", {
            detail: {
                productId: parseInt(productId)
            }
        })
        console.log('this is in product.js --- reviewEvent: ', reviewEvent);
        eventHub.dispatchEvent(customEvent)
    }
})
```

**Comment by ajawashington** [comment]
@bpotts11 Can you complete this issue ticket? We need to know the issue you are having and if any error messages are coming up?

**Comment by bpotts11** [comment]
Had to refactor fetch to include a parameter that passed the productId as a parameter. This filtered my reviews so it only returned reviews that matched that productId, instead of all reviews. Since this is filtering my reviews, I do not have to filter later in the event listener(was previously doing this, which was wrong).
```
export const getReviews = (productId) => {
    return fetch(`${bakeryAPI.baseURL}/productReviews?_expand=rating&productId=${productId}`)
        .then(response => response.json())
        .then(parsedReviews => {
            reviews = parsedReviews
        })
}
```
Passing in the productId that was received from the event listener and rendering the data.
```
export const ReviewList = (productId) => {
    getReviews(productId)
        .then(() => {
            customerReviews = useReviews()
            render()
        })
}
```
This is listening for the clickEvent of the product and passing along the detail of productId. This is what I will pass in my ReviewList function so it will know what product was selected and only return reviews for selected product
```
eventHub.addEventListener("ReviewsClicked", event => {
    const selectedProductId = event.detail.productId
    ReviewList(parseInt(selectedProductId))
})
```

**Comment by ajawashington** [comment]
Great Explanation!

**Comment by Scott47** [comment]
Combing through resolved tickets and just seeing the resolution. Great job @bpotts11  !
