### ISSUE TITLE
Disable placeOrder button when cart is empty

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#33]
Name: Kylo Ren Rice Krispie Treats
Group: Starfigher Enterprises
Book / Chapter: Sprinkles of Joy Team Project

Have you searched the other issue tickets?
Yes

Describe your issue: We are having trouble disabling the placeOrder button.  We can clear the cart but cannot toggle the button disable.

List any error messages that appear: none.

REQUIRED What have you googled? (You must have at least 3 links related to your issue)
 1. https://www.w3schools.com/jsref/prop_pushbutton_disabled.asp
 2. https://uxmovement.com/buttons/why-you-shouldnt-gray-out-disabled-buttons/#:~:text=Going%20from%20gray%20to%20fully,opacity%20to%20make%20it%20transparent
 3. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

What have you tried? 
1. We tried setting the button to a variable and calling disable on the btn..
2.  We have tried placing the disable in the eventListener..
3.  We tried disabling the button when rendered as part of the <button> ...

Copy/paste link TO THE FILE on your branch that you are having issues with
Your link: https://github.com/nss-day-cohort-46/sprinkles-of-joy-kylo-ren-s-rice-krispie-treats/blob/main/scripts/orders/OpenCart.js

Code Snippet: N/A

**Comment by Scott47** [comment]
@nathanRomad Please provide a link to the file in your repo where this issue is.

**Comment by nathanRomad** [comment]
link added

**Comment by Scott47** [comment]
@Nathan @Loganwebb1994 @CheoR Please describe the resolution to this issue and close. Thank you!

**Comment by Loganwebb1994** [comment]
The resolution was to define the button variable outside of the conditionals. Then we insert a button or a disabled button, depending on the users type of interaction.
