### ISSUE TITLE
Trouble with asynchronous call - rendering user name on reviews

### ISSUE THREAD

**Issue by Daniel-L-Ross** [nss-day-cohort-46/How-to-Ask-for-Help#34]
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
We are rendering the users name in front of the 'stars' for each review on pageload. We tried containing the data in the module by calling on the provider when rendering the customer name, but continuously ran into errors we could not resolve. Found a work-around by calling on the api in the .then chain BEFORE the review.js module was called. Wondering if there is a way we can refactor the code to keep the data in the module it is being used in. 

#### REQUIRED List any error messages that appear:
No error messages. 

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [x] 1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
- [x] 2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
- [x] 3. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>We tried moving the getUsers into different places.
>>We used .then in multiple places to try to return a string after mapping over the array 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
review.js: https://github.com/nss-day-cohort-46/sprinkles-of-joy-mando-ice-cream-sando/blob/dr-reviews-updates/scripts/reviews/Review.js

product.js: https://github.com/nss-day-cohort-46/sprinkles-of-joy-mando-ice-cream-sando/blob/dr-reviews-updates/scripts/products/Product.js

#### Code Snippet

```
export const review = (productReviews) => {
    const reviewHTML = getCustomers()
        .then(() => {
            const allCustomers = useCustomers()
            return productReviews.map(review => {
                const customer = allCustomers.find(c => c.id === review.customerId)
                const [fname, lname] = customer.name.split(" ")

                let stars = ""
                for (let index = 0; index < review.rating; index++) {
                    stars += " ⭐ ";
                }
                let blankStars = ""
                for (let index = 0; index < 5 - review.rating; index++) {
                    blankStars += " ☆ ";
                }
                return `<div>${fname}<a href="#" id="reviewLink--${review.id}">${stars} ${blankStars}</a></div>`
            }).join("")
        })

}
```

**Comment by Scott47** [comment]
Moving `getCustomers()` to `review()` made `review()` asynchronous. Made more sense to `getCustomers()` in `ProductList()` as before to get all data before `review()` is called and keep `review` synchronous.
