### ISSUE TITLE
order history/customerId issue 

### ISSUE THREAD

**Issue by nicoletatum** [nss-day-cohort-46/How-to-Ask-for-Help#37]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X] Added label to specific project/assignment that you need help with
- [X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>customer Id is not being recognized. This effects the ability to select specific order history based on customer id

#### REQUIRED List any error messages that appear:

N/A
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> 
so many things. lots of debuggers 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/sprinkles-of-joy-canoli-clones/tree/nt-orderHistory/scripts
(anything commited with ty Aja is relevant)
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```
((i'm not sure which code to post. there were a few different components containing code that might need to be changed))

**Comment by Scott47** [comment]
@nicoletatum Please complete this ticket and add a solution when y'all finish up with Aja. Thank you!

**Comment by nicoletatum** [comment]
### Resolved!

**1. to get customer id to match the currently logged in customer's id:**
changed `${bakeryAPI.baseURL}/customers?id=${id}` to `${bakeryAPI.baseURL}/customers/${id}`

**2. to show orders specific to customer logged in:**
in the `CustomerNav` function two functions needed to be invoked(have parenthesis added)`getUserId` and` isUserLoggedIn`


_If anyone also has this problem (and/or) is unclear on anything lmk_

**Comment by ajawashington** [comment]
Great job!
