### ISSUE TITLE
"Change your password" alert when trying to register

### ISSUE THREAD

**Issue by peytonkemp** [nss-day-cohort-46/How-to-Ask-for-Help#40]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> I am receiving a Google Chrome alert message when trying to register a user.

#### REQUIRED List any error messages that appear:

"Change your password. A data breach on a site or app exposed your password. Chrome recommends changing your password on localhost:5000 now."

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [x] 1. https://support.qiscus.com/hc/en-us/articles/900002203186-Why-do-I-Get-Warning-A-data-breach-on-a-site-or-app-exposed-your-password-in-Chrome-#:~:text=Chrome%20recommends%20changing%20your%20password,them%20everywhere%20they%20were%20used.
- [x] 2. https://support.google.com/chrome/thread/23534509?hl=en
- [x] 3. https://stackoverflow.com/questions/59769206/a-data-breach-on-a-site-or-app-exposed-your-password-chrome-recommends-changing

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> registering with different user info.
trying to login after I get the alert doesn't allow me to login either.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by Scott47** [comment]
That's just google saying your password is not safe. Just choose to continue when you get the alert. Nothing to worry about @peytonkemp
