### ISSUE TITLE
Undefined rendering in DOM

### ISSUE THREAD

**Issue by emilycentko** [nss-day-cohort-46/How-to-Ask-for-Help#42]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Trying to get Review value of property "review" to render to each menu item on ProductList.js. For each item, it is rendering "undefined" from Product.js

#### REQUIRED List any error messages that appear:
None

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [x] 1. https://stackoverflow.com/questions/17959154/console-says-javascript-array-is-undefined-but-im-able-to-log-its-contents
- [x] 2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
- [x] 3. https://medium.com/javascript-scene/handling-null-and-undefined-in-javascript-1500c65d51ae

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Tried debugging within render function and console.logging. Debugger lists recognized array for productReviews/appropriate saved reviews and console logs it, but not able to recognize review. I've also tried both .find() and .filter(), adding arguments to functions instead of global scope.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/nss-day-cohort-46/sprinkles-of-joy-death-star-danishes/blob/ec-save-review/scripts/products/ProductList.js

#### Code Snippet

```
const render = () => {
  contentTarget.innerHTML = bakeryProducts.map(product => {
    const productCategory = bakeryCategories.find(category => category.id === product.categoryId)

    const productReviews = bakeryReviews.filter(review => review.productId === product.id)
    console.log(productReviews)

    return Product(product, productCategory, productReviews)
  }).join("")
}
```

**Comment by Scott47** [comment]
@emilycentko You are filtering through productReviews in ProductLlist.js. This a returns an array that you are passing to `Product()`. If you want to render info from that array, you need to use `.map()` to loop through the array and render `${productReviews.review}`. Also, you are not using the variable on line 3 of `Product.js`. You can delete that.

**Comment by emilycentko** [comment]
Solution:

Review array productReviews was coming up as undefined along with review in ProductList.js when filtering bakeryReviews. Refractored Product.js to render each review per product and set a ternary/conditional since some products would not have that data, and mapped over the array to render review(s) when it existed for that related product.

New code snippet:

```
${productReviews.length !== 0 ? productReviews.map(review => {
        return `<div>${review.review}</div>`
         }) : `<div>No product reviews yet</div>`}
```
