### ISSUE TITLE
Permission/Git Issues with first React app

### ISSUE THREAD

**Issue by blusanders** [nss-day-cohort-46/How-to-Ask-for-Help#43]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>

Multiple issues with first react app install
sudo resolved creating app
I can see the spinning React logo if issued sudo npm start

Haven't had git permission issues with any other project

Could not create init git w out sudo
git remote add origin git@github.com:blusanders/kennels.git

second command was fine
git branch -M main

third had issue

#### REQUIRED List any error messages that appear:

error: could not lock config file .git/config: Permission denied
error: Unable to write upstream branch configuration
hint: 
hint: After fixing the error cause you may try to fix up
hint: the remote tracking information by invoking
hint: "git branch --set-upstream-to=origin/main".
error: update_ref failed for ref 'refs/remotes/origin/main': cannot lock ref 'refs/remotes/origin/main': unable to create directory for .git/refs/remotes/origin/main
Everything up-to-date

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [x] 1. https://stackoverflow.com/questions/32084684/error-could-not-lock-config-file-filepath-git-config-permission-denied
- [x] 2. https://github.com/skwp/dotfiles/issues/675
- [x] 3. https://intellipaat.com/community/16962/could-not-lock-config-file-git-config-permission-denied-in-jenkins-build

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

Tried sudo
Sudo and typing my password doesn't seem like a reasonable long term fix for git commands but can't get any further to see

Don't really want to do anything more by myself with permissions

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by blusanders** [comment]
git checkout -b bs-kennelsfirst

required sudo to checkout a new branch

Error w out sudo:
fatal: cannot lock ref 'refs/heads/bs-kennelsfirst': Unable to create '/Users/blufordsanders/workspace/kennels/.git/refs/heads/bs-kennelsfirst.lock': Permission denied

**Comment by blusanders** [comment]
sudo -s 

allows me to sudo without the issuing the sudo command

**Comment by blusanders** [comment]
Tried a push after commit:

➜  kennels git:(bs-kennelsfirst) gpo bs-kennelsfirst 
The authenticity of host 'github.com (140.82.113.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

**Comment by Scott47** [comment]
I think this has to do with npm permissions since this didn't occur prior to us using npm packages and the paths where access is denied in your terminal 
![image](https://user-images.githubusercontent.com/48926189/109056214-c8793480-76a5-11eb-9bb2-981b6e791378.png)

Pasting the resource I shared on slack [here](https://flaviocopes.com/npm-fix-missing-write-access-error/)

**Comment by blusanders** [comment]
I deleted and reinstalled the app after all that and it seemed to install correctly but now I'm just not sure.

**Comment by blusanders** [comment]
Just updating as I get errors:

I can't save files in VS Code without using Sudo

**Comment by jakefroeb** [comment]
https://linuxize.com/post/linux-chown-command/
how to change ownership of a file

**Comment by jakefroeb** [comment]
https://www.chriswrites.com/how-to-change-file-permissions-using-the-terminal/
changing permissions for files

**Comment by Scott47** [comment]
@blusanders Will you please add your solution to this issue and close it.

**Comment by blusanders** [comment]
Solution!

Per Nathan's similar issue, issued this command to change the permissions in the Workspace dir:
**sudo chown -R 501:20 "/Users/blufordsanders/workspace/"**

ls -l 
shows permissions changed from root to my username

created a testreact app w npx create with no errors

created a new Git repo and cloned down with no errors

am able to edit and save files with no errors

**Comment by nathanRomad** [comment]
![Screen Shot 2021-02-24 at 2 15 21 PM](https://user-images.githubusercontent.com/74743980/109530016-e1099600-7a7b-11eb-9b80-c157ddfa4ccb.png)
