### ISSUE TITLE
Keep getting module not found error

### ISSUE THREAD

**Issue by Ccourter11** [nss-day-cohort-46/How-to-Ask-for-Help#44]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> I am trying to get one of the customer components to render in JSX and I keep getting a module not found error, but I cant find my mistake..

#### REQUIRED List any error messages that appear:

Module not found: Can't resolve './components/CustomerCard' in '/home/calvin/workspace/kennels/src'

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ x] 1. https://stackoverflow.com/questions/16163176/module-not-found-error-in-node-js
- [ x] 2. https://www.digi.com/blog/post/module-not-found
- [ x] 3. https://forum.freecodecamp.org/t/react-project-module-not-found/306830

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
tried renaming my export statements, triplechecked all my import statements
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/Ccourter11/kennels/blob/main/src/index.js#L1

#### Code Snippet

```
import React from "react"
import "./Customer.css"

export const CustomerCard = () => (
    <section className="customer">
        <h3 className="customer__name">Hannah Hall</h3>
        <div className="customer__address">Psherman 42 Wallabay</div>
    </section>
)
```

**Comment by jisie** [comment]
So this code is from the chapter and we are not doing everything in the chapter yet. Follow the instructions we slacked out in the cohort channel.

**Comment by jisie** [comment]
But this is because you are trying to use a component without importing it. In the component where you are using `CustomerCard`, have you imported it?

**Comment by Ccourter11** [comment]
ah on my index.js I had import { CustomerCard } from "./components/customer"

 now I have import { CustomerCard } from "./components/customer/CustomerCard" and it works ^_^ !
