### ISSUE TITLE
zsh: command not found: react-router-dom

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#46]
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [X] Added label to specific project/assignment that you need help with
- [X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
I am trying to run the react-router-DOM in my root directory for kennels.

#### REQUIRED List any error messages that appear:
zsh: command not found: react-router-dom

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
It sends me into stackOverflow hell and I don't understand the issue with zsh....

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>not sure what to do or try next.. still a newbie when it comes to issues within terminal.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
**Your link:**  n/a

#### Code Snippet   n/a

**Comment by Scott47** [comment]
@nathanRomad Please add the links you searched to this issue to complete the ticket. You can include [this as one of your links](https://www.npmjs.com/package/react-router-dom). 

What I am understanding is that you are trying to run react-router-dom from your terminal. The chapter wants you to install react-router-dom with  `npm install --save react-router-dom` . What output are you getting when you run this?

**Comment by jisie** [comment]
Along with what's suggested above, I would recommend including exactly the part in the chapter you are going through that is causing the error. You can either copy/paste it or add a link to it. That way we have context into what caused the error.

**Comment by nathanRomad** [comment]
I just ran the wrong command.  Here is the correct command from the chapter.  my mistake.

npm i --save react-router-dom
touch src/components/ApplicationViews.js
mkdir src/components/nav
touch src/components/nav/NavBar.js
touch src/components/nav/NavBar.css
