### ISSUE TITLE
Making Pottery at the Wheel

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#48]
#### Have you searched the other issue tickets? If not, do that first. 
- [X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [X] Added label to specific project/assignment that you need help with
- [X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
I am looking to get some clarification on the current assigment... I don't know why my brain is mush but I am not understanding what I need to do...

#### REQUIRED List any error messages that appear:
None

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://stackoverflow.com/questions/12272239/javascript-function-returning-an-object
- [ ] 2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions
- [ ] 3. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment

#### REQUIRED: What have you tried? Tell us everything you have tried. 
I have created my makePottery function... I have called it in main.js..
I am missing something simple and not understanding what I need to do next..

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with
**Your link:**   https://github.com/nss-day-cohort-46/hairy-potter-nathanRomad/blob/863e76d18e38e350617b5cab9595abbe1e28bf5a/src/scripts/PotteryWheel.js#L1

#### Code Snippet
```
export const makePottery = (shape, weight, height) = {
    let potteryPiece = {
        shape: "",
        weight: "",
        height: "",
        id: ++1
    }
    return potteryPiece
}
```

**Comment by jisie** [comment]
I do see a typon where you initialize id on line 6:
```
id: 1d
```

Other than that, it looks ok. Once you've called the function from `main.js` and console logged to make sure it's worked, I think you can push up to Github and move to the next section in the README.

**Comment by nathanRomad** [comment]
I am not able to see my console.logs
I know I am missing something simple... my brain is mush and I don't know why I can't see any console.logs.

**Comment by nathanRomad** [comment]
```
let potteryId = 1

export const makePottery = (shape, weight, height) => {
  const pottery = {
    "shape": shape,
    "weight": weight,
    "height": height,
    "id": potteryId
  }

  potteryId++

  return pottery
}
```

**Comment by jisie** [comment]
Make sure you are running your server, and make sure the server is running from the right place. There's a note in the instructions on where to run your server from. 

Also, where are you placing your console logs? I don't see any in the code you have pushed up.

**Comment by nathanRomad** [comment]
in main.js
```
// Imports go first
import { makePottery } from "../scripts/PotteryWheel.js"

let mug = makePottery(mug, 4, 8)
console.log('mug: ', mug);

let plate = makePottery(plate, 6, 2)
console.log('plate: ', plate);

let bowl = makePottery(bowl, 4, 4)
console.log('bowl: ', bowl);

let cup = makePottery(cup, 6, 6)
console.log('cup: ', cup);

let servingTray = makePottery(servingTray, 2, 8)
console.log('servingTray: ', servingTray);

firePottery(mug, 2100)
firePottery(plate, 1900)
firePottery(bowl, 2200)
firePottery(cup, 2300)
firePottery(servingTray, 2150)

```

**Comment by nathanRomad** [comment]
PASS  test/pottery.create.test.js
  Creating pottery
    ✓ Pottery object is created with correct properties (5ms)
The first test is passing but I can't see my console.logs..

**Comment by nathanRomad** [comment]
Thank you Jisie, 
I read the note but missed that index.html was located in SRC and I was running my server from the root directory of my application and missing index.html entirely.

*** I missed this note in the chapter***
Note: All of the code for this project will be created the src directory of the project. Open a new terminal session, and cd to the project directory. Then you can cd src to change to that directory in your terminal. To check what's already in the src directory, use the ls command to see its contents.
