### ISSUE TITLE
I can't get my server running, missing npm start package?

### ISSUE THREAD

**Issue by kylieanyce** [nss-day-cohort-46/How-to-Ask-for-Help#49]
#### Name:
Kylie

#### Book / Chapter: 
Hairy Potter

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> I am trying to serve my app. Began with typing 'serve' and saw it was a react app, so I cancelled that. I impatiently hit ctrl+c again to close and it "force-closed all open sockets". Then tried "npm start" and get an err message - "missing script: start". 

#### REQUIRED List any error messages that appear:
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kylieanyce/.npm/_logs/2021-02-26T15_49_06_084Z-debug.log

#### REQUIRED What have you googled? **
npm error missing script start
can i still edit an app after force-closing all open sockets

- [x] 1. https://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start
- [x] 2. https://techoverflow.net/2019/04/01/how-to-fix-npm-err-missing-script-start/
- [x] 3. https://github.com/npm/npm/issues/16173

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>I tried following the instructions on the techoverflow link except replacing main... I'm not sure what they want me to replace it with. I feel index.js is correct. Now I'm googling stuff

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/hairy-potter-kylieanyce/blob/kb-makePottery/package.json

**Comment by jisie** [comment]
This is a JS application so you will use `serve` to run your server. To run your tests, you will use `npm run test`. Let us know if you are still having trouble running the server.

**Comment by kylieanyce** [comment]
That's what I thought, then I saw the react folders in the DOM. So we aren't doing anything with the DOM and are just using the console?

**Comment by jisie** [comment]
No, if you follow the instructions, by the end of all the steps, you will see output on the DOM

**Comment by kylieanyce** [comment]
@jisie got it! So, why is my console.log not working? Am I suppose to be doing it in vanilla javascript or using react? Vanilla JS doesn't seem to work, I think I'm doing it correctly for React but not sure, also doesn't seem to work. Let me know if I should create a new issue for this..

**Comment by kylieanyce** [comment]
Okay so the problem was that I was running my server from the hairy potter root directory instead of the src directory. @ajawashington Thanks for the help!
