### ISSUE TITLE
Terminal Issues

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#51]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [ X] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X ] Added label to specific project/assignment that you need help with
- [ X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Had to restart my computer. Now my terminal says "zsh: corrupt history file"

#### REQUIRED List any error messages that appear:
 see above "describe issue"

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://shapeshed.com/zsh-corrupt-history-file/ 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Looked up the problem but hesitant to try something incase I break something else

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet
zsh: corrupt history file /home/dn/.zsh_history
```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by jisie** [comment]
@AndreaMays Can you still run commands in your terminal?

**Comment by AndreaMays** [comment]
@jisie yes. Before I had to restart my computer, i had the test running. But the test stopped running and came back with a message that something was "leaking". 

I didn't know if this was a problem.

Also, now I'm completely stuck on this potterywheel test. Do I have to put in another help ticket for that

**Comment by Scott47** [comment]
Tried ```
cd ~
mv .zsh_history .zsh_history_bad
strings .zsh_history_bad > .zsh_history
fc -R .zsh_history
```
The strings command did not work, so `.zsh_history_bad` was not written to `.zsh_history`. The other commands worked, we think. @AndreaMays please close this issue if the above solution worked. If not, just reply to this issue.
