### ISSUE TITLE
Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by dylanmorris51** [nss-day-cohort-46/How-to-Ask-for-Help#56]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [ x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Rendering HTML to dom but the test won't pass

#### REQUIRED List any error messages that appear:

Cannot read property 'innerHTML' of null

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://forum.freecodecamp.org/t/cannot-set-property-innerhtml-of-undefined/235753
- [ ] 2. https://stackoverflow.com/questions/9003270/uncaught-typeerror-cannot-read-property-innerhtml-of-null
- [ ] 3. https://gamedev.stackexchange.com/questions/166154/i-keep-coming-across-an-error-cannot-read-property-innerhtml-of-undefined

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

Tried renaming my pot variables to ornament and platter since that was the example in terminal and tried refactoring with a forEach instead of for of loop.

Thought the solution was fixing a typo ```constentTarget``` fixed to ```contentTarget``` but it did nothing for the test

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/hairy-potter-dylanmorris51/blob/33166a8e4ce9efc8143a169cb55148ffa0389b49/src/scripts/PotteryList.js#L29
#### Code Snippet

```
export const PotteryList = () => {
    
    const potteryArray = usePottery()
    // console.log('potteryArray: ', potteryArray);
    let potteryHTML = ""
    // debugger

    for (const pot of potteryArray){
        potteryHTML += `
        <section class="pottery" id="pottery--${pot.id}">
        <h2 class="pottery__shape">${pot.shape}</h2>
        <div class="pottery__properties">
        Item weighs ${pot.weight} grams and is ${pot.height} cm in height
        </div>
        <div class="pottery__price">
        Price is $${pot.price}
        </div>
        </section>
        `
    }
    
    
    return contentTarget.innerHTML += 
    `
    ${potteryHTML}
    `

}
```

**Comment by Scott47** [comment]
where have you defined `contentTarget` ? Are you selecting an element on the DOM with `document.querySelector()` ?

**Comment by blusanders** [comment]
Do we comment on these issues if we are having similar issues?

**Comment by Scott47** [comment]
Sure @blusanders . Anyone on the team can respond.

**Comment by Scott47** [comment]
@dylanmorris51 where are you with this?

**Comment by blusanders** [comment]
Copy.   I too am having this issue. No console errors with innerHTML but the test is showing innerHTML errors. DOM rendering properly. Something is off, but can't quite find it yet. Just FYI.

**Comment by hrlnsnchz** [comment]
I came here to comment exactly what Blu did. Everything looks fine, but the test is not passing.

**Comment by Scott47** [comment]
@hrlnsnchz You have to conform to the test. You can get the correct output, but if your function says to return a specific html string, then your string has to match exactly.

**Comment by hrlnsnchz** [comment]
@Scott47 does that mean I have to change my data to fit what the test has? For example: the shape, weight and height of the pots.

**Comment by Scott47** [comment]
Yep. Your function and the output has to conform to the test.

**Comment by dylanmorris51** [comment]
SOLVED:

The instructions specify ```**In the main.js module**, invoke the PotteryList component function. Take its return value and _update the inner HTML_ of the article element you created above```

To meet this criteria of the test I had to refactor my code so that PotteryList()  ONLY returns a single string of HTML.

Then, on main.js I capture that return value, store it in a variable, and set innerHTML to that variable on main.js

##Main.js
```
let **potteryHTML** = PotteryList()
document.querySelector(".potteryList").innerHTML = **potteryHTML**
```
##PotteryList.js
```
export const PotteryList = () => {
    
    const potteryArray = usePottery()
    
    return potteryArray.map(pot => {

        return  `
            <section class="pottery" id="pottery--${pot.id}">
                <h2 class="pottery__shape">${pot.shape}</h2>
                <div class="pottery__properties">
                    Item weighs ${pot.weight} grams and is ${pot.height} cm in height
                </div>
                <div class="pottery__price">
                    Price is $${pot.price}
                </div>
            </section>
        `
    }).join("")

}
```

**Comment by ajawashington** [comment]
@blusanders @hrlnsnchz check out Dylan's solution!

**Comment by blusanders** [comment]
Interesting. Esp bc it's doing things in main.js that we don't normally do.

I'm all set too now. Thanks all.

**Comment by ajawashington** [comment]
> Interesting. Esp bc it's doing things in main.js that we don't normally do.
> 
> I'm all set too now. Thanks all.

Yes and that is because the test is looking for that on page load, so you have to refactor it differently. The code works but the test won't past.
