### ISSUE TITLE
Creating 5 new pieces of pottery

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#57]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added label to specific project/assignment that you need help with
- [ x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>

#### REQUIRED List any error messages that appear:

none
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment] 1. 
- [ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters] 2. 
- [ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
i have tried using the debugger within the function. I have also tried creating new pottery Items

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/hairy-potter-Younique98/blob/main/src/scripts/main.js
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```
<section class="pottery">

<div class="pottery__shape>shape: square</div>
<div class="pottery__weight>weight: 110</div>
<div class="pottery__height>height: 5</div>
<div class="pottery__height>height: 1</div>
<button id="increment--1">Incrememted</button>
</section>

**Comment by jisie** [comment]
@Younique98 Could you please describe what the issue is? I'm not sure what to look for without knowing the problem. 

Also, it looks like there is lots of code in `main.js` that the instructions do not ask for. Please make sure you are reading the instructions and doing exactly what it asks you to do.

**Comment by Younique98** [comment]
I misunderstood the directions when making the pottery pieces as I thought they needed to be an array of objects but it was just asking to create them within the variable. 
for example line this 
let madePottery = makePottery("square", 110, 5)

and not like this
const pickles: [
{pickles: 1,
picklesColor: purple}
]
