### ISSUE TITLE
Tests Keeps Failing

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#58]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> I think my code is correct and I have zero issues. Howevver, my tests aren't running.  I don't know if it's a code issue or a terminal issue.  

#### REQUIRED List any error messages that appear:

● Test suite failed to run

    Cannot find module '../src/scripts/PotteryList.js' from 'dom.test.js'

    > 1 | import { PotteryList } from "../src/scripts/PotteryList.js"
        | ^
      2 | import { makePottery } from "../src/scripts/PotteryWheel.js"
      3 | import { firePottery } from "../src/scripts/Kiln.js"
      4 | import { toSellOrNotToSell } from "../src/scripts/PotteryCatalog.js"

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:296:11)
      at Object.<anonymous> (test/dom.test.js:1:1)

Test Suites: 4 failed, 4 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        11.372s
Ran all test suites.
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://stackoverflow.com/questions/54277015/npm-test-command-is-not-running
- [ ] 2. https://github.com/preactjs/preact-cli/issues/555
- [ ] 3. https://www.reddit.com/r/node/comments/2i6wjb/having_a_problem_running_tests_with_npm_test/

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
Checked code and other tickets.  I also tried sudo chown.  That didn't work either. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
Not applicable -- I think. 
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```
let potteryPieceId = 1

export const makePottery = (shapePottery, weightPottery, heightPottery) => {
const potteryPiece = { 
    "shapePottery": shapePottery,
    "weightPottery": weightPottery, 
    "heightPottery": heightPottery,
    Id: potteryPieceId++
}
console.log(potteryPiece)
return potteryPiece
}

main.js

import { makePottery} from "./PotteryWheel.js"

// Make 5 pieces of pottery at the wheel
let mug = makePottery()

console.log(mug)

**Comment by jisie** [comment]
In the instructions, it says the object that is returned need to have very specific keys.

```
The makePottery function must return an object with the following properties on it.
shape
weight
height
id (increment this value each time the function is invoked)
```

When you console log, does your object have those properties?

**Comment by jashah46** [comment]
I've changed my code to make it read exactly the way you've written, however, I not getting the test to pass at all.  I know it's lunch and you all have instructors meeting.  I'll move on the chapters right now.  Thank you!

**Comment by jisie** [comment]
The `makePottery ` function. Does the number of parameters in the function definition match the number of arguments in the function call?

**Comment by jashah46** [comment]
Yes, the numbers match.

**Comment by jashah46** [comment]
It's 1:11, I'm stepping away for 10. Be back by 1:21.

**Comment by jashah46** [comment]
Sorry guys, I looked at #59, and also the one referred to within that.  I'm lost.

**Comment by jashah46** [comment]
Had an extra parameter ('id') being passed through.
