### ISSUE TITLE
Failing to add pottery objects to they array of pottery for sale

### ISSUE THREAD

**Issue by Loganwebb1994** [nss-day-cohort-46/How-to-Ask-for-Help#60]
**_Ticket MUST be completed before getting help from an instructor_**

#### Name:
Logan
#### Group:
N/A
#### Book / Chapter: 
pottery catalog
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ x] Added label to specific project/assignment that you need help with
- [x ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
I am having trouble getting an object to add to an array.. 

#### REQUIRED List any error messages that appear:

No errors, array is empty when I console log
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. not sure what to google in this situation
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>at this point I have refactored my code a hundred times and am a little lost

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/hairy-potter-Loganwebb1994/blob/LW-pricing/src/scripts/PotteryCatalog.js
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by Scott47** [comment]
The instructions say that the parameter for that function should be an object, not an array. Make sure you are reading the directions very carefully. Then, think about the method you would use to add something to an array.

**Comment by Loganwebb1994** [comment]
Oh shoot. yup. Thanks @Scott47

**Comment by Loganwebb1994** [comment]
@Scott47 Here is a link after refactor. I am technically passing the requirements but the tests dont like it. Im not getting any errors and everything looks right on my end.

https://github.com/nss-day-cohort-46/hairy-potter-Loganwebb1994/blob/LW-pricing/src/scripts/PotteryCatalog.js

**Comment by Loganwebb1994** [comment]
I needed to be returning the object instead of the array I was pushing it to. RESOLVED
