### ISSUE TITLE
Test 2

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#61]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Stuck on if/else statement

#### REQUIRED List any error messages that appear:
 no error message

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://www.dyn-web.com/tutorials/object-literal/properties.php
- [ ] 2.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else
- [ ] 3.  https://stackoverflow.com/questions/21562659/can-i-write-an-if-statement-within-a-javascript-object-when-setting-an-attribute

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> talking it out to myself. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by ajawashington** [comment]
Hey, could you add a code snippet of link to you code please?

**Comment by AndreaMays** [comment]
Had to make sure I was doing the dot notation inside of the if/else statement and not before the statement.
  
potteryObj.fired = true
debugger
    if (tempOfKiln > 2200) {
        
        potteryObj.cracked = true
    }else{
         potteryObj.cracked = false
    }
    return potteryObj
}
