### ISSUE TITLE
Array stays empty after get function is called

### ISSUE THREAD

**Issue by kjk1325** [nss-day-cohort-46/How-to-Ask-for-Help#62]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X ] Added label to specific project/assignment that you need help with
- [X ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> ProductTypes array continues to be empty after getProductTypes is called, so ProductList cannot read category of undefined

#### REQUIRED List any error messages that appear:

TypeError: Cannot read property 'category' of undefined

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://stackoverflow.com/questions/48363998/two-providers-in-a-react-component
- [ ] 2. https://stackoverflow.com/questions/54927811/reactjs-fetch-method-returns-empty-array
- [ ] 3. https://stackoverflow.com/questions/64601966/why-am-i-getting-and-empty-array-when-fetching-an-api-with-react-hooks

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Tried putting get functions in separate useEffect(). Double checked provider wrapping and syntax in provider, used debugger to look for obvious mistakes. asked Jake to look, added dependency to getProductTypes useEffect()

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
      const productType = productTypes.find(type => type.id === product.productTypeId)

#### Code Snippet

```
  return (
    <div className="products">
      {console.log("productList: Render", products)}
      {
      products.map(product => {
      const productType = productTypes.find(type => type.id === product.productTypeId)
      console.log('prodType: ', productType);
      
      return <ProductCard key={product.id} product={product} productType={productType} />
    })
    }
    </div>
  )
```

**Comment by kjk1325** [comment]
For some reason everything worked on refresh without any changes. I refreshed again and it's broken again

**Comment by jakefroeb** [comment]
```const { products, getProducts } = useContext(ProductContext)
    const { productTypes, getProductTypes} = useContext(ProductTypeContext)

    useEffect(() => {
        getProducts()
        .then(getProductTypes)
    },[])
```

**Comment by kjk1325** [comment]
Calling getProductTypes and putting getProducts in the .then has mine working on every refresh now

```
useEffect(() => {
	getProductTypes()
  .then(getProducts)
    }, [])
```

**Comment by jisie** [comment]
@kjk1325 Is this working now or it only works if you refresh the page?

**Comment by kjk1325** [comment]
It's working now whether refreshing or using navbar
