### ISSUE TITLE
undefined shows up in customers array after getCustomers is called

### ISSUE THREAD

**Issue by nch66862** [nss-day-cohort-46/How-to-Ask-for-Help#63]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>I am calling getCustomers inside a useEffect function. The customers array does not appear on page refresh (empty array) but does appear when I save a change and react auto-refreshes for me. I want the name of the logged in user to display on the home page. But fundamentally, I want to know why I cannot access the array of customers when I do a getCustomers.then on page load.

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://www.digitalocean.com/community/tutorials/how-to-call-web-apis-with-the-useeffect-hook-in-react
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>Changing this 
```     const getCustomers = () => {
        return fetch("http://localhost:8088/customers")
            .then(res => res.json())
            .then(setCustomers)
    }
``` 
to this 
``` const getCustomers = () => {
        return fetch("http://localhost:8088/customers")
            .then(res => res.json())
            .then(result => setCustomers(result))
    } 
``` 
and console logging among the steps. Looking at how it worked in customerList

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:https://github.com/nch66862/kennel/blob/nc-loggingUserInChp10/src/components/Home.js**

#### Code Snippet

```
let [loggedInUser, setUser] =  useState({
        name: "you are not logged in"
    })
    const { customers, getCustomers } = useContext(CustomerContext)

    useEffect(() => {
        getCustomers()
            .then(() => {
                const userId = parseInt(localStorage.getItem("kennel_customer"))
                console.log(userId)
                console.log(loggedInUser)
                console.log(customers)
                if (userId) {
                    const newestUser = customers.find(customer => customer.id === userId)
                    if (newestUser !== undefined){
                        setUser(newestUser)
                    }
                }
                console.log(loggedInUser)
            })
    }, [])

    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            <PropsAndState yourName={loggedInUser} />
        </>
    )
```

**Comment by nch66862** [comment]
Aja was able to help me out with my initial issue! I now mostly understand why the array was initially empty. My code has been refactored to look like this:
```
export const Home = () => {
    const userId = parseInt(localStorage.getItem("kennel_customer"))
    let [user, setUser] =  useState({})

    const { customers, getCustomers } = useContext(CustomerContext)

    useEffect(() => {
        console.log("useEffect")
        debugger
        getCustomers()
    }, [])
    console.log('userId: ', userId);
    const newestUser = customers.find(customer => customer.id === userId)
    console.log('newestUser: ', newestUser);
    if (newestUser !== undefined){
        console.log(newestUser)
        debugger
        setUser(newestUser)
    }

    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            <PropsAndState yourName={user} />
        </>
    )
}
```
However, I am stuck now in an infinite rendering loop and I do not know why. I have searched for answers using the "useState render loop" search in google but have not been able to implement a solution. I am assuming that the "user" variable is being rewritten every time the code is ran making react think it has changed state but I do not know how to stop that loop.

**Comment by nch66862** [comment]
I am able to break out of the infinite loop by implementing a counter but the name does not render to the DOM even though the correct user object appears in the console.

```
let i = 0
export const Home = () => {
    const userId = parseInt(localStorage.getItem("kennel_customer"))
    const [user, setUser] = useState({})

    const { customers, getCustomers } = useContext(CustomerContext)

    useEffect(() => {
        console.log("useEffect")
        // debugger
        getCustomers()
    }, [])

    const newestUser = customers.find(customer => customer.id === userId)

    if (newestUser !== undefined && i < 2) {
        console.log(newestUser)
        // debugger
        setUser(newestUser)
        i++
    }

    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            <PropsAndState yourName={user} />
        </>
    )
}
```

**Comment by Scott47** [comment]
Okay. I also have questions about this. I cloned down @nch66862 's repo and ran this branch. I got rid of `PropsAndState` component and all of the logic related to the counter and tried a second `useEffect()` that watched for customers: 
```
useEffect(() => {
        getCustomers().then(() => {
            const newestUser = customers.find(customer => customer.id === userId)
            setUser(newestUser)
        })
    }, [customers])
    ```
This did not work. The second useEffect fired after the first but the customers array was empty and I am still struggling to understand why. 

What I did next was get the rid of the `useState({})` hook contained in `[ user, setUser ]` at the top of the `Home` component and did this instead: 
```
import { React, useContext, useEffect, useState } from "react";
import { CustomerContext } from "./customer/CustomerProvider";

export const Home = () => {
    const userId = parseInt(localStorage.getItem("kennel_customer"))
    
    const { customers, getCustomers } = useContext(CustomerContext)
    
    useEffect(() => {
        console.log("useEffect")
        // debugger
        getCustomers()
    }, [])

    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            {customers.map(customer => {
                if (customer.id === userId) {
                return (<div id="user">{customer.name}</div>)
                }
        })}
        </>
    )
}
```
Moving the work of logic of through the customers array to the return worked. However, it did not work with a `.filter()` or `.find()` method which caused an error `Unhandled Rejection (Error): Objects are not valid as a React child`. But I digress.

@jisie  I am still unable answer @nch66862 's original question of why we could not access the array of customers when we needed it. I saw the same output that Nick did where the correct customer object was coming back with the find method, but no rendering.

**Comment by Scott47** [comment]
Okay, @nch66862, here is what was happening. Your `useState()` hook at the top of the component has an initial state of an empty object.
```
const [user, setUser] = useState({})
```
Initial render happens, then state changes, then re-render. The `useEffect()` hook that gets you your customers runs after the initial render. Because the initial state contained in the `user` variable is an empty object, there is no property name. So, we set the initial state contained in the `user' variable to an object with the property `name:` and the value of that property to an empty string. I implemented the second `useEffect()` I mentioned above to watch for a state change in the variable `customers`. This fires after the first useEffect that gets customers. Here is the code:  

```
import React, { useState, useEffect, useContext } from 'react'
import { CustomerContext } from './customer/CustomerProvider'

export const Home = () => {
    const [user, setUser] = useState({ })
    const userId = parseInt(localStorage.getItem("kennel_customer"))

    const { customers, getCustomers } = useContext(CustomerContext)
    console.log(customers)

    useEffect(() => getCustomers(), [])

    useEffect(() => {
        const newestUser = customers.find(customer => customer.id === userId)
        setUser(newestUser)
    }, [customers])

    return (
        <>
            { console.log(customers)}
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            <div>{user.name}</div>
        </>
    )
}
```

**Comment by nch66862** [comment]
@Scott47 So I went back in the room for Kandy Korner and Jake F said a past NSS grad protects his data when using react hooks to avoid errors. This code works and the console log shows the point at which it failed before (where it console logs "no data"). I also put a console log in the return statement. It looks like it runs the code 3 times.
```
import { React, useContext, useEffect, useState } from "react";
import { CustomerContext } from "./customer/CustomerProvider";

export const Home = () => {
    const userId = parseInt(localStorage.getItem("kennel_customer"))
    console.log('userId: ', userId);
    const [user, setUser] = useState({name: ""})

    const { customers, getCustomers } = useContext(CustomerContext)

    useEffect(() => {
        console.log("useEffect")
        getCustomers()
    }, [])

    useEffect(() => {
        console.log(customers)
        const newestUser = customers.find(customer => customer.id === userId)
        newestUser ? setUser(newestUser):console.log("no data")
    }, [customers])

    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            {console.log("rendering return statement", user)}
            <h3>Welcome, {user.name}</h3>
        </>
    )
}
```

The console:
```
[HMR] Waiting for update signal from WDS...
Home.js:6 userId:  6
Home.js:27 rendering return statement {name: ""}
Home.js:12 useEffect
Home.js:17 [{…}]
Home.js:19 no data
Home.js:6 userId:  6
Home.js:27 rendering return statement {name: ""}
Home.js:17 (6) [{…}, {…}, {…}, {…}, {…}, {…}]
Home.js:6 userId:  6
Home.js:27 rendering return statement {email: "nickcarver@amail.com", name: "Nick Carver", id: 6}
```
I suppose this method will work for now until I can learn to control the data using React!

**Comment by Scott47** [comment]
Nice @nch66862 ! I added the conditional to the code I provided in the previous comment. The conditional is what is handling the error. In fact, with that conditional, you can set inital state to an empty object without the name property. @jakefroeb 's solution is what worked. However, it has me questioning all of these useEffects() and how this would work at scale. I am also still a little fuzzy on when everything fires because my second useEffect() that should only fire with a change in customer state, appears to fire much earlier than I expect, which is why I think it worked on save without the conditional, but not on refresh.

**Comment by Scott47** [comment]
Also, with this logic, the second useEffect() is totally unnecessary. This is where my code is now:
```
useEffect(() => getCustomers().then(() => {
        const userId = parseInt(localStorage.getItem("kennel_customer"))
        const newestUser = customers.find(customer => customer.id === userId)
        newestUser ? setCurrentUser(newestUser) : console.log('nobody home')
    }), [])
    ```

**Comment by nch66862** [comment]
@Scott47 I tried to implement the single useEffect as you showed in your last post. However, the useEffect only runs one time and I get the "nobody home" console log and it does not try again. It does work on save! But not on a hard refresh.
The .then() does not seem to contain the latest value for customers when it executes.

```
import { React, useContext, useEffect, useState } from "react";
import { CustomerContext } from "./customer/CustomerProvider";

export const Home = () => {
    // const userId = parseInt(localStorage.getItem("kennel_customer"))
    // console.log('userId: ', userId);
    const [user, setUser] = useState({})

    const { customers, getCustomers } = useContext(CustomerContext)

    useEffect(() => getCustomers().then(() => {
        const userId = parseInt(localStorage.getItem("kennel_customer"))
        console.log("customers", customers)
        const newestUser = customers.find(customer => customer.id === userId)
        newestUser ? setUser(newestUser) : console.log('nobody home')
    }), [])

    console.log("customers", customers)
    
    return (
        <>
            <h2>Nashville Kennels</h2>
            <small>Loving care when you're not there.</small>

            <address>
                <div>Visit Us at the Nashville North Location</div>
                <div>500 Puppy Way</div>
            </address>
            <h3>Welcome, {user.name}</h3>
        </>
    )
}
```
This is wild. It has data on line 18 but not on line 13 AFTER customers has changed....
```
[HMR] Waiting for update signal from WDS...
Home.js:18 customers []
Home.js:18 customers (6) [{…}, {…}, {…}, {…}, {…}, {…}]
Home.js:13 customers []
Home.js:15 nobody home
```

**Comment by Scott47** [comment]
The initial question on this issue boiled down to no property of name on the initial state object before re-render. The conditional in useEffect resolved this issue.
