### ISSUE TITLE
Capstone Ideas

### ISSUE THREAD

**Issue by nathanRomad** [nss-day-cohort-46/How-to-Ask-for-Help#66]
#### Have you searched the other issue tickets? If not, do that first. 
This is just a review of my capstone idea for approval..

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
- [X] Added label to specific project/assignment that you need help with
- [X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
I would like to present an initial idea for my capstone.

---------------------------------------------------------------------------------------------------------------------------
Name: Nathan Hamilton
Email Address:  nathan.a.hamilton@gmail.com

Mentor’s Name: 
Capstone Repo on Github: 

Name of Project:  topFIVE
Application Overview: Allow users to create custome topFIVE lists to keep their favorites places and things in one place!
Have you ever had friends give recommendations but you never can find the recommendations later?  
Now you can track your favorite music, restaurants, and keep track of them all in one place!
Users can like & follow each others topFIVES.

What problem does your application solve? external memory / list sharing

How will your application work? 
- A user logs in and creates as many topFIVES as they want... They can like & follow other topFIVES.
Features?
- login / logout 
- CRUD topFIVES
- Follow other user created topFIVES
- share ? topFIVES ?

Why do you want to build this application? 
People love lists!  I feel like keeping track of favorite places and things is a habit that almost every person I know engages in... 

Who are the target users of this application?  EVERYONE / anyone who needs/wants to reference their favorites and other peoples favorites!  Imagine Oprahs book club always sharing their topFIVE books!

Will you have multiple types of users? If so, what can each type of user do?
I have not considered multiple user types at this time.. but would consider it.

**Comment by blusanders** [comment]
I like this idea!
