### ISSUE TITLE
Cannot read property 'map' of undefined when add customer button is clicked

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#70]
**_Ticket MUST be completed before getting help from an instructor_**

#### Name:
Thomas Witherow
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ]x Added label to specific project/assignment that you need help with
- [ x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
Im getting an undefined when trying to map animals for my add customer button.
#### REQUIRED List any error messages that appear:
TypeError: Cannot read property 'map' of undefined
CustomerForm
src/components/customers/CustomerForm.js:99
   96 | <div className="form-group">
   97 |     <label htmlFor="animalId">Animal: </label>
   98 |     <select defaultValue={customer.animalId} name="animal" id="animalId" onChange={handleControlledInputChange} className="form-control" >
>  99 |         <option value="0">Select a animal</option>
      | ^  100 |         {animals.map(a => (
  101 |             <option key={a.id} value={a.id}>
  102 |                 {a.name}
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://www.debuggr.io/react-map-of-undefined/
- [ ] 2. https://stackoverflow.com/questions/24706267/cannot-read-property-map-of-undefined/58691066
- [ ] 3. https://discuss.codecademy.com/t/typeerror-cannot-read-property-map-of-undefined/44

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
referencing similar modules, console.
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/Thomas88s/Kennels/blob/main/src/components/customers/CustomerForm.js
#### Code Snippet

```
   <div className="form-group">
                  <label htmlFor="animalId">Animal: </label>
                  <select defaultValue={customer.animalId} name="animal" id="animalId" onChange={handleControlledInputChange} className="form-control" >
                      <option value="0">Select a animal</option>
                      {animals.map(a => (
                          <option key={a.id} value={a.id}>
                              {a.name}
                          </option>
```

**Comment by Scott47** [comment]
copy pasta mistake. Had CustomerContext where should have had AnimalContext
