### ISSUE TITLE
Some questions about git 

### ISSUE THREAD

**Issue by Thomas88s** [nss-day-cohort-46/How-to-Ask-for-Help#72]
**_Ticket MUST be completed before getting help from an instructor_**

Thomas Witherow

#### Group:
 Kennels 11
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
Just had some questions about get and revisiting old branches.
I just wanted to go back to a previous point in my kennels. my codes broke and i wanted to revisit and when i switch branches its still broke. 
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by Scott47** [comment]
@Thomas88s Will you please let us know what the questions are by completing this ticket?

**Comment by Thomas88s** [comment]
nm

**Comment by Scott47** [comment]
@Thomas88s if you are going to close this issue, please make sure you are adding a solution. So, for this ticket, you'll need to add the original question and the solution before closing the issue. If you need assistance with this, please let one of us know.

**Comment by Thomas88s** [comment]
I just wanted to go back to a previous point in my kennels. my codes broke and i wanted to revisit and when i switch branches its still broke.

I still had uncommitted changes that were not allowing me to switch branches. After deleting the changes I was able to switch. I then looked up the branches i had on my local machine and checked out into the one that was appropriate.
