### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#73]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [X] Added label to specific project/assignment that you need help with
- [X] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> AnimalList will return animals with the correct map function. But both CustomerList and EmployeeList are broken.

#### REQUIRED List any error messages that appear:

Cannot read property 'map' of undefined

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

1. https://www.debuggr.io/react-map-of-undefined/
2. https://stackoverflow.com/questions/24706267/cannot-read-property-map-of-undefined/58691066
- [ ] 3.https://discuss.codecademy.com/t/typeerror-cannot-read-property-map-of-undefined/449405 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>Asking other students. Google. Staring at code

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
 return (
        <>
      <div className="customers">
        {/* {console.log("CustomerList: Render", customers)} */}
        {
          customers.map(customer => {
            return <Customer key={customer.id} customer={customer} />
          })
        }
      </div>
      </>
    )
```

**Comment by Scott47** [comment]
@AndreaMays Please send me a link to the file in your github repo.  

Also, check to make sure you have the correct Providers wrapped around your routes in `ApplicationViews`. Also, make sure you are bringing in `getCustomers` with context (i.e. `const { customers, getCustomers } = useContext()` ). If you are still getting the same error, reply here and I'll come see you.

**Comment by AndreaMays** [comment]
https://github.com/AndreaMays/kennelsReact/blob/92012b611548a289d570783d3ff553add411a3be/src/components/customer/CustomerList.js#L22

**Comment by jisie** [comment]
One thing I noticed is [here](https://github.com/AndreaMays/kennelsReact/blob/92012b611548a289d570783d3ff553add411a3be/src/components/customer/CustomerProvider.js#L11). The `.then` is expecting a function expression, not a function invocation. Please comment if that fixes the issue or if you still get the error.

**Comment by AndreaMays** [comment]
@jisie i'm a bit confused on everything right now. I took the code from animalList. I'm confused why animalList works but my code in my other lists isn't working.

**Comment by jisie** [comment]
@AndreaMays Can you try changing the line that I referenced and let me know what happens?

**Comment by AndreaMays** [comment]
@jisie yes i will try.

**Comment by Scott47** [comment]
@AndreaMays did it work?

**Comment by AndreaMays** [comment]
no.
