### ISSUE TITLE
Using .length method when optional chaining

### ISSUE THREAD

**Issue by emilycentko** [nss-day-cohort-46/How-to-Ask-for-Help#75]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Having trouble grabbing the length/number of objects (employees and animals) for locations array to render on Location.js (i.e. "3 employees and 2 animals" at a selected location)

#### REQUIRED List any error messages that appear:

none

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
- [ ] 2. https://v8.dev/features/optional-chaining
- [ ] 3. https://dev.to/macsikora/what-is-wrong-with-optional-chaining-and-how-to-fix-it-3nno

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have tried storing the array.length into a new variable ie
```
const employeeNumber = location.employees?.length
```
I've also tried making sure there was data applied to each location in my JSON and console logging location.employees?.length but it shows up as undefined.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/emilycentko/kennels/blob/ec-locations-nested-data/src/components/location/Location.js

#### Code Snippet

```
export const LocationCard = ( { location } ) => {

    return (
    <section className="location">
        <h3 className="location__name">
            <Link to={`/locations/detail/${location.id}`}>
                {location.name }
            </Link>
        </h3>
        <div className="location__number_employees">{location.employees?.length} employees</div>
        <div className="location__number_animals">{location.animals?.length} animals</div>
    </section>
    )
}
```

**Comment by jisie** [comment]
`Length` is an array method. Are you sure `location.employees` and `location.animals` is an array? Try console logging those values to check the data structure.

**Comment by emilycentko** [comment]
Looks like the fetch call I would need from getLocationById is only for one location, not an array of locations. Refactored LocationCard to call that function and get the employees/animals.length for that selected location in my return:

```
export const LocationCard = ( { location } ) => {

    const locationId = location.id

    const { getLocationById } = useContext(LocationContext)

    const [selectedLocation, setSelectedLocation] = useState({})

    useEffect(() => {
        console.log("useEffect", locationId)
        getLocationById(locationId)
        .then((response) => {
          setSelectedLocation(response)
        })
    }, [])

    return (
    <section className="location">
        <h3 className="location__name">
            <Link to={`/locations/detail/${location.id}`}>
                {location.name }
            </Link>
        </h3>
        <div className="location__number_employees">{selectedLocation.employees?.length} employees</div>
        <div className="location__number_animals">{selectedLocation.animals?.length} animals</div>
    </section>
    )

}
```

**Comment by Scott47** [comment]
Nice work @emilycentko !

**Comment by emilycentko** [comment]
Major props to @jakefroeb for helping!!
