### ISSUE TITLE
React Context routing & state variables

### ISSUE THREAD

**Issue by SubtleCo** [nss-day-cohort-46/How-to-Ask-for-Help#76]
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added label to specific project/assignment that you need help with
- [x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> I have two issues, but I believe they both revolve around the React lifecycle. My main issue lies (I think) in the structure of my data providers: If I refresh my page on the `/order` view and immediately go to the `/products` view, I'll get an undefined error. I believe this is because `<OrderList />` calls `getProducts()` in its `useEffect()` statement but not `getProductTypes()`. Then, when navigating to `/products`, the error that is thrown says that `productTypes is undefined`. Essentially, `<Product List />` is waiting on `products` to populate for its final render, and `getProductTypes()` happens first. However, if you go from `/order` to `/products`, the `products` state variable is already filled out, so the `/products` view renders with the error.

EDIT:
>>> The second issue is that a state variable (customerOrder) doesn't seem to set in a useEffect (in customer/OrderList.js), which causes the order page not to load when refreshed. I ask this question here because I believe it all has to do with routing & useEffect(). Navigating away from /order and back fixes the issue.

#### REQUIRED List any error messages that appear:
TypeError: Cannot read property 'name' of undefined

#### REQUIRED What have you googled? 
- [x] 1. https://ozmoroz.com/2018/11/why-my-setstate-doesnt-work/
- [x] 2. https://stackoverflow.com/questions/30782948/why-calling-react-setstate-method-doesnt-mutate-the-state-immediately
- [x] 3. https://reactjs.org/docs/conditional-rendering.html

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I have tried changing the order of my state setters in my useEffects, calling them multiple times, using conditional rendering, debugging, console.logging, changing where my state variables are set, etc.

#### REQUIRED: 
https://github.com/SubtleCo/NSS-Kandy-Korner/blob/dabe9827f9d89832afc3b96e78830666271ceeda/src/components/products/ProductList.js#L11

#### Code Snippet

ProductList:
```
export const ProductList = () => {
    const { products, getProducts } = useContext(ProductContext)
    const { productTypes, getProductTypes } = useContext(ProductTypeContext)

    useEffect(() => {
        getProductTypes().then(getProducts)
    }, [])


    return (
        <section className="products">
            {console.log(products)}
            {console.log(productTypes)}
            {
                products.map(product => {
                    const productType = productTypes.find(pT => pT.id === product.productTypeId)
                    return <ProductCard key={product.id} product={product} productType={productType}/>
                })
            }
        </section>
    )
}
```

OrderList: 
```
export const OrderList = () => {
    const { customerId, customerOrder, setCustomerOrder } = useContext(CustomerContext)
    const { products, getProducts } = useContext(ProductContext)
    const { customerProducts, getCustomerProducts } = useContext(CustomerProductContext)

    useEffect(() => {
        getCustomerProducts()
            .then(getProducts)
            .then(() => {
                const thisCustomersProducts = customerProducts.filter(cP => cP.customerId === customerId)
                setCustomerOrder(thisCustomersProducts)
            })
    }, [])

    return (
        <section className="customerOrder">
            <h2 className="customerOrder__title">Your Order</h2>
            {
                customerOrder.map(customerProduct => {
                    const product = products.find(p => p.id === customerProduct.productId)
                    return <OrderCard key={customerProduct.id} product={product} />
                })
            }
        </section>
    )
}
```

**Comment by ajawashington** [comment]
@SubtleCo So the first thing is that your customerOrderContext is not being used the way you think. Right now, you have a "click n buy" kinda thing there is no order that needs to be considered. Your CustomerProducts is your order. So in your first UseEffect() on OrderList just getProducts, then getCustomerProducts and remove the additional things. Then in your render map through the customerProducts where the customerId is equal current id.

On your ProductList remove, the question mark on the .find method.

**Comment by SubtleCo** [comment]
@ajawashington That makes a ton of sense! I'm still confused as to why my customerOrder isn't getting set in that useEffect, though - shouldn't it?

**Comment by jisie** [comment]
```js
useEffect(() => {
        getProducts()
            .then(getCustomerProducts)
    }, [])

    useEffect(() => {
        console.log(customerProducts)
        const thisCustomersProducts = customerProducts.filter(cP => cP.customerId === customerId)
        setCustomerOrder(thisCustomersProducts)
    }, [customerProducts])
```

Setting state is an asynchronous process. So a `.then` will not necessary wait for the set state to be done. The the best way to do something when state changes is to have a useEffect that contains that state variable in the dependency.

**Comment by SubtleCo** [comment]
Beautiful, thank you!
