### ISSUE TITLE
Editing JSON database error: Unexpected token T

### ISSUE THREAD

**Issue by dylanmorris51** [nss-day-cohort-46/How-to-Ask-for-Help#77]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Code is breaking when I click "Save" button after editing an animal

#### REQUIRED List any error messages that appear:

```
Unexpected token T at JSON position 0
```

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. https://daveceddia.com/unexpected-token-in-json-at-position-0/
- [ ] 2. https://stackoverflow.com/questions/37280274/syntaxerror-unexpected-token-in-json-at-position-0
- [ ] 3. https://developers.suitecommerce.com/troubleshooting-uncaught-syntaxerror-unexpected-token-u-in-json-at-position-0.html

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I tried copy and pasting from the chapter but I am getting this error. Other classmates do not have this error.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**

#### Code Snippet

```
const handleSaveAnimal = () => {
        if (parseInt(animal.locationId) === 0) {
            window.alert("Please select a location")
        } else {
            //disable the button - no extra clicks
            setIsLoading(true);
            // This is how we check for whether the form is being used for editing or creating. If the URL that got us here has an id number in it, we know we want to update an existing record of an animal
            if (animalId) {
                //PUT - update
                updateAnimal({
                    id: animal.id,
                    name: animal.name,
                    breed: animal.breed,
                    locationId: parseInt(animal.locationId),
                    customerId: parseInt(animal.customerId)
                })
                    .then(() => history.push(`/animals/detail/${animal.id}`))
            } else {
                //POST - add
                addAnimal({
                    name: animal.name,
                    breed: animal.breed,
                    locationId: parseInt(animal.locationId),
                    customerId: parseInt(animal.customerId)
                })
                    .then(() => history.push("/animals"))
            }
        }
    }
```

**Comment by dylanmorris51** [comment]
No error when I "add" a new animal but error when I "edit"

**Comment by Scott47** [comment]
@dylanmorris51 Have you checked your `.json` file to make sure the data is uniform (i.e. all the same properties, etc.)?

**Comment by dylanmorris51** [comment]
@Scott47 Yes I tried that, the error seems to be something else. When I call the put method the item is deleting all keys except for id

**Comment by dylanmorris51** [comment]
Solved:

I forget to write the ``body: JSON.stringify(animal)``` line into my put call
