### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#78]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [x ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> Getting the above error. I've had this error before in our projects, but this one confuses me b/c I'm not if there is more left to do as we go through the chapters, or I did something wrong in here.  I do see that animal is just a parameter being passed through, and there is no other instance of "animal".  Also, in AnimalCard, why did we refactor to pass through 'animal' and then add curly brackets. 

#### REQUIRED List any error messages that appear:

TypeError: Cannot read property 'name' of undefined

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [x] 1. https://stackoverflow.com/questions/51650638/reactjs-typeerror-cannot-read-property-name-of-undefined
- [X ] 2.  [I didn't think this article would help me much, but since we discussed 'dependency arrays' in the previous chapter, I thought maybe it could help] https://betterprogramming.pub/understanding-the-useeffect-dependency-array-2913da504c44
- [X] 3.[ 67](uhttps://github.com/nss-day-cohort-46/How-to-Ask-for-Help/issues/67rl) & [73](https://github.com/nss-day-cohort-46/How-to-Ask-for-Help/issues/73)

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Reviewing the code, google, and prior help tickets. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/jashah46/kennels/commit/3f971d8ceeed1258d4a3d242722788011b4b6977

#### Code Snippet

```
import React from "react"
import "./Animal.css"

export const AnimalCard = () => (
export const AnimalCard = ({ animal }) => (
    <section className="animal">
        <h3 className="animal__name">Doodles</h3>
        <div className="animal__breed">Breed: Poodle</div>
        <h3 className="animal__name">{animal.name}</h3>
        <div className="animal__breed">{animal.location.name}</div>
    </section>
)

```

**Comment by SubtleCo** [comment]
Hey @jashah46 it looks like you're still calling `<Animal Card />` without any context in `Kennel.js`. Comment that out and your error goes away. Eventually your `kennel.js` will just be responsible for calling the `<NavBar>` and `<ApplicationViews>`. Looks like you've got it set up correctly in `<ApplicationViews>`, it's just the call in `kennel.js` that's angry because it's outside of an `<AnimalProvider>` context.

**Comment by Scott47** [comment]
@jashah46 Let us know if @SubtleCo 's solution works and if you'd like to go over it with any of us. Also, thank you Alex!

**Comment by jashah46** [comment]
that did the trick.  Thank you gentlemen!
