### ISSUE TITLE
 type of product shows up then doesn't as ith has one undefined and my link is not showing up

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#81]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [ x] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
My link is not showing up for my product Details
One moment it works then the next moment it doesn't work when it comes to adding the type to the dom
#### REQUIRED List any error messages that appear:

ProductCard.js:16 Uncaught TypeError: Cannot read property 'type' of undefined
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ https://reactrouter.com/web/api/Link] 1. 
- [ https://forum.freecodecamp.org/t/why-is-my-react-router-not-working/257114/3] 2. 
- [https://codeburst.io/uncaught-typeerror-cannot-read-property-of-undefined-in-javascript-c81e00f4a5e3 ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
I have tried remapping over my products and also tried to create a whole new variable to contain the product type. I also created a separate ProductTypeProvider.
#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/Younique98/KandyKorner/blob/41e84e93b0e01bf45ed6fa7df8202ff6ee4a8298/src/components/products/ProductList.js#L44
#### Code Snippet

```
filteredProducts.map(product => {
            const productType = productTypes.find(typeOfProducts => typeOfProducts.id === product.productTypeId)
          {console.log(product)}
            return <ProductCard key={product.id} productProps={product} productType={productType} />
        })
```

**Comment by jakefroeb** [comment]
try switching the order of your get requests in your first use effect getting productTypes before getting products

**Comment by Younique98** [comment]
Thank you! I’ll try that.

**Comment by Younique98** [comment]
@jakefroeb  That worked!! You are so awesome. Thank you so much. I switched it to 
`useEffect(() => {
      getProductTypes()
      .then(getProducts)
  }, [])`
