### ISSUE TITLE
Cannot destructure property 'animal' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#82]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>
Have the error message above. Similar to my last issue ticket, and did the same thing to resolve. After doing this, it resulted in the issue ticket i'm writing about.  Not sure what my next step is. 
#### REQUIRED List any error messages that appear:

Cannot destructure property 'animal' of 'undefined' as it is undefined.
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [x] 1. https://www.freecodecamp.org/news/array-and-object-destructuring-in-javascript/
- [x] 2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
- [x] 3. issue ticket [67.](https://github.com/nss-day-cohort-46/How-to-Ask-for-Help/issues/67)

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> I've re-read the chapter to make sure I didn't miss anything, and it doesn't seem like I did.  Though there was a lot of re-creating that I had to do and that could have broken something. For example, I had to create 'providers' etc. The error points me to a particular line and I've tried to follow the bouncing ball and I couldn't find the problem.  

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/jashah46/kennels/commit/a8647fa96de66982ed6e7e36a1029e9c9326f6a7

#### Code Snippet

```
import React from "react"
import "./Animal.css"


export const AnimalCard = ({ animal }) => (
    <section className="animal">
        <h3 className="animal__name">{animal.name}</h3>
```

**Comment by Scott47** [comment]
@jashah46 putting this comment here as a reminder to circle back re: refactor of `ApplicationViews`

**Comment by Scott47** [comment]
Animal Card renders after refactor of `ApplicationViews` and `Kennel.js` and deleting some old function calls in Kennel.JS
