### ISSUE TITLE
Chapter 9/10 questions

### ISSUE THREAD

**Issue by AndreaMays** [nss-day-cohort-46/How-to-Ask-for-Help#85]
**_Ticket MUST be completed before getting help from an instructor_**

#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>1. Owner will only display on my animalCard after I comment it out, refresh my page, and then while on that page go back into my code and comment that line. Why won't my owner render on page load?
2. AnimalForm is not displaying when I click the button?
3. Everytime I try to "register" a user login it says "email already exist", but I've never used that email. 
4. Error: AnimalForm "Nothing rendered/returned." but i have a "return" on my animalForm.js?

#### REQUIRED List any error messages that appear:

Error: AnimalForm "Nothing rendered/returned." but i have a "return" on my animalForm.js
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Talked with Jisie earlier about how to ask all my questions with the help ticket. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:** https://github.com/AndreaMays/kennelsReact/blob/am-kennels-ch9/src/components/animal/AnimalForm.js

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```

**Comment by Scott47** [comment]
@AndreaMays for the register issue, I would check your JSON and make sure that the properties in the .json file match the properties on the register form and every object in the .json file are exactly the same. 

For rendering `AnimalForm`, change your `<Route path="/animals/create">` to `<Route exact path="/animals/create">`

Let me know where you stand after these changes and I'll hop in your room.

**Comment by AndreaMays** [comment]
I changed the path but it still not showing up. Not sure where I went wrong but I will keep trying.

**Comment by Scott47** [comment]
curly bracket was closing function after the return and, therefore, the `AnimalForm` was not returning anything.

**Comment by Scott47** [comment]
For not rendering owner on refresh, we changed the order of fetch calls in the `useEffect()` in `AnimalForm` to 
```
useEffect(() => {
     getLocations()
     .then(getCustomers)
     .then(getAnimals)
     }, [] )
     ```
