### ISSUE TITLE
Missing README Instructions

### ISSUE THREAD

**Issue by morriscodez** [nss-day-cohort-46/How-to-Ask-for-Help#87]
#### REQUIRED Question or issue:
>> I think some instructions disappeared from the README when we reset the project. There was a section about setting up project boards and PR templates that's no longer in our README

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
nothing to see here
```

**Comment by Scott47** [comment]
@dylanmorris51 https://github.com/nss-day-cohort-46/reactive-nutshell-helm-of-friendship-1#reactive-nutshell-the-information-dashboard

**Comment by Scott47** [comment]
@dylanmorris51 you are good, here, yes? I can close this issue?

**Comment by morriscodez** [comment]
Turns out I am crazy and I'm thinking of the slack instructions on Day 46 channel
