### ISSUE TITLE
ERD Naming Convention Clarification

### ISSUE THREAD

**Issue by morriscodez** [nss-day-cohort-46/How-to-Ask-for-Help#88]
#### REQUIRED Question or issue:
>> Seeking clarification on ERD naming. We want to rename "currentUserId" and "userID" to avoid confusion but we are wondering if JSON needs "userID" in order to connect it with the "users" table. We don't know quite how to google this.

#### REQUIRED Check all that apply:
- [ x] Rubber Ducking 
- [ x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
https://dbdiagram.io/d/60465b71fcdcb6230b232094
```

**Comment by Scott47** [comment]
The convention for a foreign key in JSON is name of the entity + `Id`, with a capital 'I' and lowercase 'D'. In this specific instance, you are connecting a user to a user, so the join is connecting a `userId` to a `userId`. `currentUserId` would be the currently logged in user and the `userId` would be that users friend. You can change the naming if it helps. Understanding the relationship is what is most important here. This make sense @dylanmorris51

**Comment by morriscodez** [comment]
Understanding the relationship being the important thing does make sense.

```currentUserId``` being the logged in user makes sense and ```userId``` being the logged in user's friend makes sense.

Just to make sure I do understand you correctly; can we change the names in the ```Messages``` table to be ```senderId``` and ```receiverId```

So  connect ```senderId```(messages) to ```currentUserId``` (friends)

and connect ```receiverId```(messages) to ```userId```(friends)

Would this be a violation of JSON rules/conventions?

**Comment by Scott47** [comment]
@dylanmorris51 messages is a one to many relationship. This is a public chat forum where a user can post a message and see other users messages, but this is not  like a user to user DM.
