### ISSUE TITLE
[QUICK ISSUE]

### ISSUE THREAD

**Issue by nicoletatum** [nss-day-cohort-46/How-to-Ask-for-Help#90]
#### REQUIRED Question or issue:
>> not sure about location of delete button. we are trying to decide if it should it go in list/form/card/elsewhere 

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
N/A
```

**Comment by ajawashington** [comment]
@nicoletatum I think the card would be a great place to put it.

**Comment by Scott47** [comment]
We think the card should a good spot for it. Let me know if you want me to pop in to discuss @nicoletatum

**Comment by nicoletatum** [comment]
i agree, but i think a quick pop in would be helpful @Scott47 @ajawashington whoever is free for a sec

**Comment by ajawashington** [comment]
@Scott47 test to see comments

**Comment by Scott47** [comment]
test @Scott47

**Comment by Scott47** [comment]
test for c46-help-repo @nicoletatum

**Comment by Scott47** [comment]
reopening to test comment @nicoletatum
