### ISSUE TITLE
Cannot Login Using Provided Login Data

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#94]
#### REQUIRED Question or issue:
>> Using me@me.com, I have json and npm running 

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
No code.  Get pop-up saying "user does not exist".
```

**Comment by ajawashington** [comment]
Json-server running in the wrong directory.
