### ISSUE TITLE
Event Form not POSTing and Saving

### ISSUE THREAD

**Issue by emilycentko** [nss-day-cohort-46/How-to-Ask-for-Help#95]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> I cannot get my input data in my events form to POST/save, and I think it has to do with my useEffect

#### REQUIRED Copy/paste any error messages that appear:

When I start typing in an input field:

Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at div
    at fieldset
    at form
    at EventForm (http://localhost:3000/static/js/main.chunk.js:1357:63)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:34545:29)
    at EventProvider (http://localhost:3000/static/js/main.chunk.js:1792:85)
    at ApplicationViews
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:34545:29)
    at Nutshell
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:34180:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:33800:35)

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://reactjs.org/docs/hooks-effect.html
- [ ] 2. https://reactjs.org/docs/hooks-reference.html
- [ ] 3. https://stackoverflow.com/questions/62248741/how-to-apply-useeffect-based-on-form-submission-in-react

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> Using getEvents and setEvents, using events as a parameter / consulting code from Kennel/Checked Provider

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/reactive-nutshell-shield-of-swiftness-1/blob/ec-events-form/src/components/events/EventForm.js

#### Code Snippet

```
const handleSaveEvent = () => {
        event.preventDefault()

        if (event.name === "" || event.date === "" || event.location === "") {
            window.alert("Please complete the field")
        } else {
            addEvent(event)
            .then(() => history.push("/events"))
        }
    }

    useEffect(() => {
        getEvents()
    }, [])
```

**Comment by ajawashington** [comment]
@emilycentko you are not passing an event in the handleSaveEvent args. 
`const handleSaveEvent = (event) => {}`

**Comment by emilycentko** [comment]
@ajawashington I just tried that and get a new error when I try to submit the form: TypeError: Converting circular structure to JSON.

**Comment by jakefroeb** [comment]
make sure the event you are passing into the provider is the event you created not the event created on click. For example the event.preventDefault() is a different event than the event.name

**Comment by ajawashington** [comment]
@emilycentko what @jakefroeb said!

**Comment by emilycentko** [comment]
Would you mind explaining that a bit more @jakefroeb? I think I'm still a bit unclear!

**Comment by ajawashington** [comment]
@emilycentko first I would change event.preventDefault to e.preventDefault so it is different. And it know the event being passed through is the event you want to save.

**Comment by emilycentko** [comment]
I just added the following code into my handleControlledInputChange function and that did it! But I'm not exactly sure what that does or why

```
if (e.target.id.includes("Id")) {
            inputValue = parseInt(inputValue)
        }
```
