### ISSUE TITLE
Auto-fill edit form

### ISSUE THREAD

**Issue by calebsjames** [nss-day-cohort-46/How-to-Ask-for-Help#97]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x] Added to `c46 Help-Thread` project board
- [x] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>> When editing a message, I can either auto fill the text area with the message content being edited or I can edit the message but I can't do both.

#### REQUIRED Copy/paste any error messages that appear:

No errors

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ ] 1. https://goshakkk.name/react-forms-for-editing/
- [ ] 2. https://stackoverflow.com/questions/44431416/auto-fill-in-react-doesnt-work
- [ ] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> setIsLoading/useState function. Renaming the values I am targeting.

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link: https://github.com/nss-day-cohort-46/reactive-nutshell-talisman-of-havocing/pull/38/files#diff-3adb75e9369841ab4bac6d12ac518384a5b32a4c6a897529d2661723d8dc4bd6

#### Code Snippet

```

import React, { useContext, useEffect, useState } from "react"
import { useHistory, useParams } from "react-router-dom";
import { MessageContext } from "./MessageProvider";




export const MessageEdit = (id) => {
    const { editMessage, getMessageById } = useContext(MessageContext)
    const {messageId} = useParams()
    const [isLoading, setIsLoading] = useState(true);
    const history = useHistory();
    
    let thisMessage = {}

    
    getMessageById(parseInt(messageId))
    .then(res => thisMessage = res)

    const [message, setMessage] = useState({
        date: thisMessage.date,
        text: thisMessage.text,
        userId: sessionStorage.getItem("nutshell_user")
        
    });
    

    useEffect(() => {
        if (messageId) {
            getMessageById(messageId)
                .then(message => {
                    setMessage(message)
                    setIsLoading(false)
                })
        } else {
            setIsLoading(false)
        }
    }, [])

    console.log("this message", message)

    
    const handleControlledInputChange = (event) => {
      
      const editMessage = { ...message }
      let selectedVal = event.target.value
      editMessage[event.target.id] = selectedVal
      // update state
      setMessage(editMessage)
    }

    const handleSaveMessage = () => {
        editMessage({
            id: thisMessage.id,
            date: thisMessage.date,
            text: message.text,
            userId: sessionStorage.getItem("nutshell_user")
        })
            .then(() => history.push("/messages"))
        
    }
      
    
    console.log("thisMessage.text", thisMessage)
    return (
      <form className="messageForm">
        <h2 className="messageForm__title">Edit Post</h2>
        <fieldset>
          <div className="form-group">
            <textarea id="postText"  autoFocus className="form-control"
            onChange={handleControlledInputChange}
            value={message.text}
            >{message.text}</textarea>
            
          </div>
        </fieldset>
        
        <button className="btn btn-primary"
          
          onClick={event => {
            event.preventDefault()
            handleSaveMessage()
          }}>
        Save Edit</button>
      </form>
    )
}

```

**Comment by Scott47** [comment]
@calebsjames I'm wondering if the `event.preventDefault()` inside the form is preventing all default behavior. What happens if you move the `event.preventDefault()` to the `handleSaveMessage()` function?

**Comment by calebsjames** [comment]
> @calebsjames I'm wondering if the `event.preventDefault()` inside the form is preventing all default behavior. What happens if you move the `event.preventDefault()` to the `handleSaveMessage()` function?

I tried this implementation but it did not have any discernible effect. Thanks for the suggestion!

**Comment by Scott47** [comment]
@calebsjames in your `useState`, your keys do not match up with the input field. `textarea` has a id of `postText` and the state variable has a key of text. Because the `handleControlledInputChange()` uses the id of the element of the key, that id has to be the same as the key/value pair you are trying to change.

**Comment by calebsjames** [comment]
> @calebsjames in your `useState`, your keys do not match up with the input field. `textarea` has a id of `postText` and the state variable has a key of text. Because the `handleControlledInputChange()` uses the id of the element of the key, that id has to be the same as the key/value pair you are trying to change.

This was it. Thanks Scott!
