### ISSUE TITLE
API not parsing to json

### ISSUE THREAD

**Issue by jakefroeb** [nss-day-cohort-46/How-to-Ask-for-Help#98]
**_Ticket MUST be completed before getting help from an instructor_**
#### Have you searched the other issue tickets? If not, do that first. 
- [x ] Yes

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added to `c46 Help-Thread` project board
- [x ] Added the `Blocker` label if this is stoping you from moving forward

#### REQUIRED Describe your issue:
>>
when i try to parse my response into json i get the error

#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**
- [ x] 1. https://stackoverflow.com/questions/37269808/react-js-uncaught-in-promise-syntaxerror-unexpected-token-in-json-at-posit
- [ x] 2. dont know where else to look
- [ x] 3. nothing i google seems to be helpful

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> postman my get request looks fine, rewriting function checking for spellling, calling the function in a different place

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**https://github.com/nss-day-cohort-46/reactive-nutshell-garment-of-illusions-1/blob/jhf-weather-weatherProvider/src/components/weather/WeatherProvider.js**

#### Code Snippet

```
const getTodaysWeather = () => {
        return fetch(`api.openweathermap.org/data/2.5/weather?q=Nashville&appid=8f01d52d478e3ec2c957316c7958823d`)
        .then(res => res.json())
    }
```

**Comment by jisie** [comment]
@jakefroeb Your URL is missing `http://` at the beginning

**Comment by jakefroeb** [comment]
shame
and dissappointment....
postman lied to me and made my error go away

**Comment by SubtleCo** [comment]
Honestly it's because the OpenWeather documentation doesn't have http:// in the url. bummer summer.

**Comment by jakefroeb** [comment]
and because it works in postman without it
