### ISSUE TITLE
Github Shows Conflicts But Don't See On VSCode

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#99]
#### REQUIRED Question or issue:
>> did PR. showed conflicts.  Went into code and didn't see any conflicts.  We've worked together for about 20 mintues, trying to resolve it, but are afraid of breaking the app. 

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x ] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
N/A
```

**Comment by Scott47** [comment]
needed to `git merge main` to see conflicts in VSCode.
